优先选择偏好类型数据源，不需要等其他源查询完毕
open-ani/ani pull request #1002
Opened 2024-09-24 06:31 UTC by NieR4ever

resolve #816

2024-09-24 09:34 UTC, Him188 requested changes
需要增加测试, 当一个源完成后就立即选择

2024-09-24 09:34 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/fetch/MediaFetcher.kt
> +
```suggestion
class CompletedCondition(
    val webCompleted: Boolean,
    val btCompleted: Boolean,
    val localCacheCompleted: Boolean,
) {
    val allCompleted: Boolean get() = webCompleted && btCompleted && localCacheCompleted

```

2024-09-24 09:34 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/fetch/MediaFetcher.kt
> +
这里会丢失类型安全特性, 假如未来增加一个 kind, 但是没有修改这部分代码, 这部分就不悄悄地工作了

2024-09-24 09:34 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/fetch/MediaFetcher.kt
> +    val localCacheCompleted: Boolean,
应该用 map 吧, 用 EnumMap 可以保证类型安全

2024-09-24 09:34 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/fetch/MediaFetcher.kt
> +
否则这个 class 能被构造出异常状态, 例如前三个属性都是 false, 最后一个属性 true

2024-09-24 09:34 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/selector/MediaSelector.kt
> +    val preferKind: Flow<MediaSourceKind?>
does not make much sense to be in MediaSelector

2024-09-24 09:34 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/selector/MediaSelector.kt
> +    val preferKind: Flow<MediaSourceKind?>
应当 MediaSelectorAutoSelect 自己接收这个

2024-09-24 09:35 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/fetch/MediaFetcher.kt
> +    val localCacheCompleted: Boolean,
see `me.him188.ani.app.data.source.media.selector.MediaSelectorSubtitlePreferences`

https://github.com/open-ani/ani/blob/19c3069cb3f63381e08020aca99c8936bf30587a/app/shared/app-data/src/commonMain/kotlin/data/source/media/selector/MediaSelectorSubtitlePreferences.kt#L28

2024-09-25 16:31 UTC, NieR4ever commented
不清楚怎么测试，感觉比较难观察 hasCompleted 的变化

2024-09-25 17:28 UTC, Him188 reviewed
Looks good, 但是需要有 test 确保以后不会 regress

需要测试:
- prefer BT 时, WEB 完成了, 应当继续等待
- prefer BT 时, BT 完成了, 应当自动选择
- prefer BT 时, 没有启用 BT 源, 会怎么样?
- prefer BT 时, 但 BT 没有搜到东西, 是什么行为?
- 没有 preferefence, BT 完成了但 web 没有完成, 应当继续等待
- 没有 preferefence, 都完成了, 自动选择 (应该是现有 case?)

2024-09-25 17:28 UTC, Him188 commented
test 中协程是单线程的, 你可以控制的

2024-09-27 20:40 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/fetch/MediaFetcher.kt
> +value class CompletedConditions(
```suggestion
class CompletedConditions(
```

这个东西看起来会用在被 box 的地方, 那其实不需要 `value`

2024-09-27 20:40 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/fetch/MediaFetcher.kt
> +                        else -> false
为什么要有 `null`? 不能用 `false` 吗

2024-09-27 20:40 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/fetch/MediaFetcher.kt
> +            combine(map) { pairs ->
目前两个 combine 的算法会导致启动数倍多的协程

用一个 combine 就足够解决问题了, 让 combine 的 lambda 返回 `ImmutableEnumMap<MSK, Boolean>`

2024-09-27 20:40 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/fetch/MediaFetcher.kt
> +            val map = MediaSourceKind.entries.map { kind ->
目前这样改会为那些原本总是期待所有数据源加载完成的代码增加计算量 (计算是否完成并构造 EnumMap 等), 导致性能变差

这是可以避免的, 我觉得可能要做一个另外的属性来支持中间状态

2024-09-27 20:40 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/fetch/MediaFetcher.kt
> +    fun copy(
未使用, 没必要有

2024-09-27 20:40 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/fetch/MediaFetcher.kt
> +    val values: EnumMap<MediaSourceKind, Boolean?>
make it private

2024-09-27 20:40 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/data/source/media/selector/MediaSelectorAutoSelectTest.kt
> +        val completableDeferred = CompletableDeferred<Unit>()
feels like weired

这个应该由每个 caller 自己构造使用

2024-09-27 20:40 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/data/source/media/selector/MediaSelectorAutoSelectTest.kt
> +        preferKind: MediaSourceKind? = MediaSourceKind.BitTorrent,
这三个属性会关键地影响 test 结果, 在这个场景不应当有默认值

2024-09-27 20:40 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/data/source/media/selector/MediaSelectorAutoSelectTest.kt
> +            flowContext = EmptyCoroutineContext,
这会导致内存泄露, 应当使用 runTest 里的 backgroundScope (现有的那些代码就是内存泄露)

2024-09-27 20:40 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/data/source/media/selector/MediaSelectorAutoSelectTest.kt
> +        this.mediaList.value = mediaList
这看起来可能会意外地影响 test 的结果
我感觉应当至少保持一个其他类型的

2024-09-27 20:40 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/data/source/media/selector/MediaSelectorAutoSelectTest.kt
> +    fun `awaitCompletedAndSelectDefault selects one when prefer bt and bt done`() = runTest {
我觉得要新加一个 section 表示这些是来测试 "
优先选择偏好类型数据源，不需要等其他源查询完毕" 的, 否则未来的人可能不会知道这些 case 的用途

2024-09-27 20:40 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/data/source/media/selector/MediaSelectorAutoSelectTest.kt
> +            flowContext = EmptyCoroutineContext,
memory leak

2024-09-27 20:40 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/data/source/media/selector/MediaSelectorAutoSelectTest.kt
> +            configProvider = { MediaFetcherConfig.Default },
当用处超过两个就最好弄一个 `createMediaSourceFetcher`. 否则未来给 `MediaSourceMediaFetcher` 增加参数时要修改很多地方. 如果有 createMediaSourceFetcher 就只需要改一个地方

2024-09-27 20:40 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/data/source/media/selector/MediaSelectorAutoSelectTest.kt
> +        webEnabled: Boolean = true,
```suggestion
        addBtSources: Boolean = true,
        addWebSources: Boolean = true,
```

说明它的直接意图

2024-09-29 08:46 UTC, NieR4ever commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/fetch/MediaFetcher.kt
> +                        else -> false
当 prefer bt数据源，但bt数据源都 disable 时，btCompleted 总是 false 会使 awaitCompletion 无法结束，返回 null 可以让 awaitCompletion 根据 completedConditions.allCompleted() 判断是否结束
```kt
        mediaFetchSession.awaitCompletion { completedConditions ->
            return@awaitCompletion preferKind.first()?.let {
                completedConditions[it]
            } ?: completedConditions.allCompleted()
        }

```

2024-09-29 10:58 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/source/media/fetch/MediaFetcher.kt
> +                        else -> false
ok，那留个注释吧

2024-09-29 15:16 UTC, Him188 approved these changes

2024-09-30 00:29 UTC, merged