jbr jcef
open-ani/ani pull request #1038
Opened 2024-10-02 13:37 UTC by StageGuard

Gradle JVM Toolchain is locked to JBR-JCEF 17.

2024-10-03 02:50 UTC, StageGuard commented
需要改进的问题：

* CI 构建改成 JBR
* jbr bin 里的 icudtl.dat ， jcef_helper.exe 和 v8_context_snapshot.bin 没被打包，需要写个 task 手动复制
* MacOS test

2024-10-03 07:01 UTC, StageGuard commented
ping @Him188

2024-10-03 08:42 UTC, Him188 commented
我觉得可以

2024-10-05 17:25 UTC, Him188 requested changes

2024-10-05 17:25 UTC, Him188 commented on app/desktop/build.gradle.kts
> +                val toolchainHome = Jvm.current().javacExecutable.parentFile
that's incorrect. use javaHome like what i did

2024-10-05 17:45 UTC, Him188 commented on app/desktop/build.gradle.kts
> +                val toolchainHome = Jvm.current().javacExecutable.parentFile
and you did not specify inputs & outputs

2024-10-06 09:30 UTC, merged