进度条跟随滑动手势
open-ani/ani pull request #602
Opened 2024-07-21 07:33 UTC by NieR4ever

resolve #574

2024-07-21 07:43 UTC, Him188 reviewed
滑动时，如果 controller 没有显示，那就应该显示 controller。理想情况下还只应该显示进度条

2024-07-21 07:43 UTC, Him188 commented on app/shared/video-player/common/ui/guesture/SwipeSeekerState.kt
> +            onDragging: SwipeSeekerState.() -> Unit = {},
`rememberDraggableState` 的那个参数也是叫这个名字吗

2024-07-21 07:43 UTC, Him188 commented on app/shared/video-player/common/ui/guesture/VideoGestureHost.kt
> +                                    0f
如果 total 是 0 就不该 preview 吧

2024-07-21 07:44 UTC, Him188 commented on app/shared/video-player/common/ui/guesture/SwipeSeekerState.kt
> +            onDragging: SwipeSeekerState.() -> Unit = {},
这里不要有 receiver，用户能自己拿到

2024-07-21 08:43 UTC, NieR4ever commented on app/shared/video-player/common/ui/guesture/SwipeSeekerState.kt
> +            onDragging: SwipeSeekerState.() -> Unit = {},
@Composable
public fun rememberDraggableState(
    onDelta: (Float) -> Unit
): DraggableState

2024-07-21 10:59 UTC, Him188 commented on app/shared/video-player/common/ui/guesture/SwipeSeekerState.kt
> +            onDragging: SwipeSeekerState.() -> Unit = {},
no, onDelta 更准确

2024-07-21 12:01 UTC, Him188 commented on app/shared/video-player/common/ui/guesture/VideoGestureHost.kt
> +                                controllerState.isVisible = true
在滑动结束后需要隐藏自动控制器

2024-07-21 14:47 UTC, Him188 requested changes
如果不实现仅显示进度条, 我觉得现在应该不要自动显示控制器. 全屏沉浸播放视频的时候显示全部控制器是影响体验的

2024-07-21 14:47 UTC, Him188 commented on app/shared/video-player/common/ui/guesture/VideoGestureHost.kt
> +                            },
如果控制器本身就是开着的 (不是由滑动才导致他开的), 那就不应该关闭它

否则会导致在安卓上本来是显示控制器, 滑动了一下后关掉了

2024-07-22 21:34 UTC, Him188 requested changes
增加 preview (参考 `PreviewVideoScaffold`)

2024-07-22 21:34 UTC, Him188 commented on app/shared/video-player/common/ui/guesture/VideoGestureHost.kt
> +                        var currentVisible by remember { mutableStateOf(VisibleState.INVISIBLE) }
```suggestion
                        var previousVisible by remember { mutableStateOf(VisibleState.INVISIBLE) }
```

2024-07-22 21:34 UTC, Him188 commented on app/shared/video-player/common/ui/VideoControllerState.kt
> +enum class VisibleState(var value: Boolean) {
```suggestion
enum class ControllerVisibility(val value: Boolean) {
```

2024-07-22 21:34 UTC, Him188 commented on app/shared/video-player/common/ui/VideoControllerState.kt
> +enum class VisibleState(var value: Boolean) {
```suggestion
enum class ControllerVisibility(val topBar: Boolean, val bottomBar: Boolean, val floatingBottomEnd: Boolean, val rhsBar: Boolean)
```
分别表示各个部分的 visibility

2024-07-22 21:34 UTC, Him188 commented on app/shared/video-player/common/ui/VideoControllerState.kt
>  @Stable
format 一下这个文件

2024-07-22 21:34 UTC, Him188 commented on app/shared/video-player/common/ui/guesture/VideoGestureHost.kt
> +                                }
我觉得应该类似于 `VideoControllerState.setRequestAlwaysOn` 那样实现一个 `setRequestProgressBarVisible`, 由 `VideoControllerState` 去处理状态

2024-07-22 21:34 UTC, Him188 commented on app/shared/video-player/common/ui/VideoControllerState.kt
> +    var isVisible: VisibleState by mutableStateOf(initialVisible)
```suggestion
    var visibility: VisibleState by mutableStateOf(initialVisible)
```

2024-07-22 21:34 UTC, Him188 commented on app/shared/video-player/common/ui/VideoControllerState.kt
> +    initialVisible: VisibleState = VisibleState.VISIBLE
```suggestion
    initialVisibility: VisibleState = VisibleState.VISIBLE
```

2024-07-22 21:34 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +            }
这个逻辑应该放在 VideoScaffold 里面做, 可增加一个 slot `detachedProgressSlider` 用来传入这个特殊显示的 slider. padding 也应该在 slot container 里做, 最好让 `MediaProgressSlider` 自己不需要设置  padding

2024-07-22 21:34 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +            val showProgressSliderOnly = derivedStateOf {
没有 remember

`by remember {`

2024-07-22 21:34 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                videoControllerState.isVisible.takeIf { it != VisibleState.INVISIBLE } ?: previousVisibleState
这个逻辑太复杂, 我没看懂

2024-07-22 21:34 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +            var previousVisibleState by remember { mutableStateOf(VisibleState.VISIBLE) }
这个东西能工作实际上是一个 bug

为什么需要这个? 应当依赖 controllerState.visibility 就足够了

2024-07-22 21:34 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                        downloadingColor = if (isInDebugMode()) Color.Yellow else aniDarkColorTheme().surface,
有两个地方有相同的这个逻辑是容易导致未来忘记改其中一边的, 我觉得可以增加一个 `PlayerControllerDefaults. MediaProgressSlider()`, 其中 `downloadingColor` 的默认值为这个表达式

2024-07-22 21:34 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                Box {
这个 Box 是多余的

2024-07-22 21:34 UTC, Him188 commented on app/shared/video-player/common/ui/guesture/GestureLock.kt
> +    controllerVisible: () -> VisibleState,
```suggestion
    controllerVisibility: () -> VisibleState,
```

2024-07-22 21:34 UTC, Him188 commented on app/shared/video-player/common/ui/guesture/GestureLock.kt
> +    setControllerVisible: (visible: VisibleState) -> Unit,
```suggestion
    setControllerVisibility: (visibility: VisibleState) -> Unit,
```

将属性从 boolean 修改为多元后, 也需要对应修改它的用法变量名

2024-07-22 21:39 UTC, Him188 commented on app/shared/video-player/common/ui/VideoControllerState.kt
> +enum class VisibleState(var value: Boolean) {
其实还能更进一步用 `value class` 实现, 把这些值都 pack 到一个 int 里 (用 bit 表示), 不过这点空间我们就没必要节省了

2024-07-22 21:40 UTC, Him188 commented on app/shared/video-player/common/ui/VideoControllerState.kt
> +enum class VisibleState(var value: Boolean) {
VisibleState 很通用, 会污染全局命名空间, 我个人希望避免这样

2024-07-23 01:29 UTC, NieR4ever commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                        downloadingColor = if (isInDebugMode()) Color.Yellow else aniDarkColorTheme().surface,
https://github.com/open-ani/ani/pull/602#discussion_r1687159855
似乎和这个冲突了

2024-07-23 02:39 UTC, NieR4ever commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +            if (showProgressSliderOnly == ControllerVisibility.DetachedSliderOnly) {
https://github.com/open-ani/ani/pull/602#discussion_r1687161098
https://github.com/open-ani/ani/pull/602#discussion_r1687161642
这段代码修复了一个controller切换的bug
bug的逻辑是：在发生隐藏动画的过程中，videoControllerState.visibility会从Visible->Invisible ，或者从DetachedSliderOnly->Invisible ，此时如果使用videoControllerState.visibility== ControllerVisibility.DetachedSliderOnly会在隐藏动画未完成的情况下发生组件切换
所以需要通过previousVisibilityState 保存上一个状态（Visible或DetachedSliderOnly），在videoControllerState.visibility切换为Invisible 的时候使用previousVisibleState阻止隐藏动画发生时controller bar和detached slider的切换

2024-07-23 07:46 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                        downloadingColor = if (isInDebugMode()) Color.Yellow else aniDarkColorTheme().surface,
不冲突吧

2024-07-23 09:33 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodePage.kt
> +                initialControllerVisible = ControllerVisibility.Visible,
```suggestion
                initialControllerVisibility = ControllerVisibility.Visible,
```

2024-07-23 09:33 UTC, Him188 commented on app/shared/video-player/common/ui/guesture/VideoGestureHost.kt
> +                        }
`setRequestProgressBarVisible` in `onDragStarted`, and `cancelRequestProgressBarVisible()` in `onDragStopped` sounds better to me

See the exisiting `controllerState.setRequest` for an example.

2024-07-23 09:34 UTC, Him188 commented on app/shared/video-player/common/ui/guesture/VideoGestureHost.kt
> +                        }
Sorry my Chinese IME is not working

2024-07-23 09:49 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +            if (showProgressSliderOnly == ControllerVisibility.DetachedSliderOnly) {
That's indeed a problem that I have missed when proposing the new visibility design. I have to check the details before I can tell a solution.

The current solution does not look like nice to me, as it's complex and I failed to understand it without your explaination. At least we should add some comments.

This logic should be inside VideoControllerState

2024-07-24 03:22 UTC, NieR4ever commented
https://github.com/open-ani/ani/pull/602#discussion_r1687163961
不清楚是不是这样做

2024-07-24 17:37 UTC, Him188 reviewed
progressBarVisible 那个逻辑我感觉比较怪

2024-07-24 17:37 UTC, Him188 commented on app/shared/video-player/common/ui/VideoControllerState.kt
> +            ?: previousVisibility) == ControllerVisibility.DetachedSliderOnly
不要用 `== ControllerVisibility.DetachedSliderOnly`, 用里面的属性 `.detachedSlider`

2024-07-24 17:37 UTC, Him188 commented on app/shared/video-player/common/ui/VideoControllerState.kt
> +        (_visibility.takeIf { it != ControllerVisibility.Invisible }
不要依赖 != `Invisible`

2024-07-24 17:37 UTC, Him188 commented on app/shared/video-player/common/ui/VideoControllerState.kt
>      }
这个实现看起来怪怪的

2024-07-24 17:38 UTC, Him188 commented
改了之后, 点一下 "Resolve conversation"

2024-07-26 11:07 UTC, Him188 commented
@StageGuard 你有好的实现想法吗, 我主要觉得这个算法不靠谱

2024-07-26 11:39 UTC, Him188 reviewed
有一些场景需要考虑
1. invisible 时开始滑动屏幕, 此时要只显示进度条 (动画淡入), 滑动完成动画淡出
2. visible 时滑动屏幕, 此时不要更改状态, 淡出时要确保布局不变

corner case:
3. 在 invisible 滑动时, 第二个手指点击屏幕, 会触发显示控制器
4. 在 visible 滑动时, 第二个手指点击屏幕, 会隐藏

----

- 考虑使用 Crossfade 替换 bottomBar 部分, 三个状态
- 需要为 `VideoControllerState` 增加单元测试 (在 `desktopTest` 里写)

2024-07-27 09:05 UTC, NieR4ever commented
单击然后快速滑动会出现bug

https://github.com/user-attachments/assets/3cd77b85-7434-4900-8cb0-cc68d766d0bf

2024-07-27 09:58 UTC, Him188 commented
> 单击然后快速滑动会出现bug

没录鼠标我看得不是很明白, 但是我觉得这个问题不大

2024-07-27 10:00 UTC, StageGuard commented
在视频还没加载好的时候不应该能使用这个手势

2024-07-27 10:24 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                animationSpec = tween(400),
这里我倾向于使用默认的 (300ms), 有什么特殊理由用 `tween(400)` 吗

2024-07-27 10:24 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                    ControllerVisibility.Visible ->
不要用 `ControllerVisibility.Visible` 判断, 它只能在赋值的时候使用, 否则使用这种设计的优势就完全没有了. 使用它里面的单独的属性例如 `detachedSlider`

2024-07-27 10:24 UTC, Him188 commented on app/shared/video-player/common/ui/VideoControllerState.kt
> +        val Visible = ControllerVisibility(
```suggestion
        @Stable
        val Visible = ControllerVisibility(
```
下面几个同理. 如果这个东西会在 composable 代码里面使用到, 增加 `@Stable` 可以轻微优化性能

2024-07-27 10:24 UTC, Him188 commented on app/shared/video-player/common/ui/VideoControllerState.kt
>  @Stable
这里建议增加一个空行

2024-07-27 10:24 UTC, Him188 commented on app/shared/video-player/common/ui/VideoControllerState.kt
> +    }
这个逻辑比较奇怪.

试试以下方案? 

```kotlin
    private val progressBarRequesters = SnapshotStateList<Any>()
    /**
     * 请求显示进度条
     * 当目前没有显示进度条时, 将显示独立的进度条. 
     * 若目前已经有进度条, 则会保持该状态, 防止自动关闭.
     *
     * @param requester 是谁希望请求显示进度条. 在 [cancelRequestProgressBarVisible] 时需要传入相同实例. 同一时刻有任一 requester 则会让进度条一直显示.
     */
    fun setRequestProgressBar(requester: Any) {
        if (requester in progressBarRequesters) return
        progressBarRequesters.add(requester)
    }

    /**
     * 取消显示进度条
     */
    fun cancelRequestProgressBarVisible(requester: Any) {
        progressBarRequesters.remove(requester)
    }
```

请求显示和是否真的显示, 这两个逻辑应当是独立的. 通过 `progressBarRequesters` 记录当前是否有请求, 然后再到 visibility 计算当前的状态. 只有 `VideoControllerState` 才能创建 `ControllerVisibility`, caller 只能请求显示进度条或者请求显示全部.

```kotlin
    private var fullVisible by mutableStateOf(false)
    private val hasProgressBarRequester by derivedStateOf { progressBarRequesters.isNotEmpty() }
    
    /**
     * 当前 UI 应当显示的状态
     */
    val visibility: ControllerVisibility by derivedStateOf {
        // 根据 hasProgressBarRequester, alwaysOn 和 fullVisible 计算正确的 `ControllerVisibility`
        
        return ControllerVisibility( ... )
    }

    /**
     * 切换显示或隐藏整个控制器.
     * 
     * 此操作拥有比 [setRequestProgressBar] 更低的优先级. 
     * 如果此时有人请求显示进度条, `toggleEntireVisible(false)` 将会延迟到那个人取消请求后才隐藏进度条. 
     * 如果此时没有人请求显示进度条, 此函数将立即生效.
     * 
     * @param visible 为 `true` 时显示整个控制器
     */
    fun toggleFullVisible(visible: Boolean) {
        fullVisible = true
    }
```


需要增加更多测试用例:

1. fullVisible false 时一个人请求
2. fullVisible false 时一个人请求然后取消请求
3. fullVisible false 时一个人请求然后 fullVisible true

以上事件顺序排列组合一下

2024-07-27 10:25 UTC, Him188 commented
> 在视频还没加载好的时候不应该能使用这个手势

准确来说应该是还没获取到视频长度 (为 `0`) 的时候.

2024-07-28 17:59 UTC, Him188 commented
Unfortunately 有不少冲突, 主要是文件移动了位置, 我猜 IDE 能自动处理

2024-07-31 07:50 UTC, Him188 reviewed
最新的commit饶了一圈，不能直接在手势加一个 enableSwipeToSeek 吗

2024-07-31 07:50 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                    videoPropertiesState!!.durationMillis != 0L
用 let 来避免使用 !!

2024-07-31 07:50 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +            LaunchedEffect(videoPropertiesState) {
看起来不应该用 launchedEffect

2024-07-31 07:50 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/guesture/SwipeSeekerState.kt
> +    var enabled: Boolean by mutableStateOf(true)
这应当是一个内在属性，要由state内部使用这个属性，而不是在外面 if enabled

2024-07-31 13:59 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                    }
`with` is stange here

```suggestion
                    videoPropertiesState?.let { it.durationMillis != 0L } ?: false
```

2024-08-01 13:28 UTC, Him188 reviewed
全部 LGTM, 但是有个小问题, 我觉得 `Crossfade` 那个部分, 应该放到 VideoScaffold 来实现?

VideoScaffold 增加一个 detachedProgressSlider 属性, 处理 layout 问题. 
EpisodeVideo 只使用 VideoScaffold, 将 slider 实现传入.

2024-08-01 13:28 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/VideoControllerState.kt
> +        if (hasProgressBarRequester) return@derivedStateOf (ControllerVisibility.DetachedSliderOnly)
```suggestion
        if (alwaysOn) return@derivedStateOf ControllerVisibility.Visible
        if (fullVisible) return@derivedStateOf ControllerVisibility.Visible
        if (hasProgressBarRequester) return@derivedStateOf ControllerVisibility.DetachedSliderOnly
```

2024-08-01 13:34 UTC, Him188 commented
备注, 
- [ ] need QA

2024-08-01 13:49 UTC, StageGuard requested changes

2024-08-01 13:49 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                    false ->
这里一个是 slot 一个不是，看起来是不是有点奇怪

2024-08-01 13:49 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +    detachedProgressSlider: @Composable () -> Unit,
必要参数必须在 `modifier` 前面

2024-08-01 15:16 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                    false ->
See also

https://github.com/open-ani/ani/pull/602#pullrequestreview-2212717404

> VideoScaffold 增加一个 detachedProgressSlider 属性, 处理 layout 问题.

2024-08-02 07:54 UTC, NieR4ever commented
使用两个AnimatedVisibility代替CrossFade之后正常使用手势功能时不会出现两个组件一起出现的情况，但在invisible时单击然后快速滑动仍会使两个组件一起出现

2024-08-02 10:24 UTC, Him188 commented
> 使用两个AnimatedVisibility代替CrossFade之后正常使用手势功能时不会出现两个组件一起出现的情况

其实两个一起出现我觉得没问题, 只要有渐变动画就可以

2024-08-02 15:34 UTC, Him188 commented
测试 OK

感觉要在 detached 模式下也显示时间, 并且让时间也跟着动可能会更好? 不过目前已经不错了

2024-08-02 15:45 UTC, Him188 approved these changes

2024-08-02 15:45 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/VideoControllerStateTest.kt
> +package ui
ide bug, 这里 package 不对

要不顺便把它挪到 commonTest 里面去吧, master 目前 commonTest 环境应该是 ok 了, commonTest 会在 android desktop ios 三个平台都跑

应该移动一下文件就好了, 代码不用改

2024-08-02 15:45 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/VideoControllerStateTest.kt
> +    private fun createState(
```suggestion
    private fun createStateRequested(
```

因为这个一定会 request 一下 (`setRequestAlwaysOn`), 所以我会倾向于函数名里面就说明

2024-08-04 07:31 UTC, Him188 approved these changes

2024-08-04 07:31 UTC, Him188 commented
好像跟刚刚合入的冲突了

2024-08-04 07:32 UTC, StageGuard approved these changes

2024-08-04 08:00 UTC, Him188 approved these changes

2024-08-04 08:38 UTC, merged