windows音量控制
open-ani/ani pull request #676
Opened 2024-07-30 04:09 UTC by NieR4ever

resolve #414 

效果图：
![image](https://github.com/user-attachments/assets/66abc55d-c19e-47d7-b432-612fb94d80af)
![image](https://github.com/user-attachments/assets/9c315157-0ba8-4757-9e8a-8d6924726ab7)
![image](https://github.com/user-attachments/assets/6e73aca4-fff5-4881-8b9c-97795e9b9cfc)
![image](https://github.com/user-attachments/assets/426c71af-c07b-47cd-b061-f40efcf4092e)

2024-07-30 04:10 UTC, NieR4ever commented
挺好的，除了第二次播放页面调整音量会导致崩溃 :(

2024-07-30 14:18 UTC, NieR4ever commented
新效果图
<img width="843" alt="Snipaste_2024-07-30_22-16-53" src="https://github.com/user-attachments/assets/eccf76ba-01a4-43bf-92ba-172d93e7e0b4">

2024-07-30 14:20 UTC, NeKoOuO commented
現在能夠滑鼠移到上面滾輪改變嗎

2024-07-30 15:09 UTC, NeKoOuO commented
瞭解 那可以用原版的來顯示

2024-07-30 20:05 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +        interactionSource: MutableInteractionSource = MutableInteractionSource(),
```suggestion
        interactionSource: MutableInteractionSource = remember { MutableInteractionSource() },
```

2024-07-30 20:05 UTC, Him188 commented on app/shared/video-player/src/desktopMain/kotlin/ui/VideoPlayer.desktop.kt
> +        player.audio().setVolume(volume.times(200).roundToInt())
times 200 有什么根据么

2024-07-30 20:06 UTC, Him188 commented
第一版我不喜欢是因为它会改变弹幕编辑器的宽度, 总感觉比较怪

2024-07-30 20:06 UTC, Him188 commented
这个需要在触摸板上测试滚动事件

2024-07-30 20:07 UTC, Him188 commented
有人写了个 vertical slider 

https://gist.github.com/Debdutta-Panda/d47a84b3e2f82b4dd4b1f0cf131e73d8

2024-07-30 20:11 UTC, Him188 commented
也可以考虑用

https://github.com/aakarshrestha/compose-vertical-slider/blob/main/composeVerticalSlider/src/main/java/com/aakarshrestha/composeverticalslider/ComposeVerticalSlider.kt

https://github.com/aakarshrestha/compose-vertical-slider

2024-07-30 23:21 UTC, NieR4ever commented on app/shared/video-player/src/desktopMain/kotlin/ui/VideoPlayer.desktop.kt
> +        player.audio().setVolume(volume.times(200).roundToInt())
```java
uk. co. caprica. vlcj. player. base. AudioApi
public boolean setVolume( int volume )
Set the volume.
The volume is actually a percentage of full volume, setting a volume over 100 may cause audible distortion.
Params:
volume – volume, a percentage of full volume in the range 0 to 200
Returns:
true if successful; false on error
```

2024-07-30 23:34 UTC, NieR4ever commented
和 #480 属于一个bug，从3.1.1开始第二次进入播放页面使用音量合成器调整音量就可以稳定复现这个bug

2024-07-30 23:54 UTC, NieR4ever commented
> 这个需要在触摸板上测试滚动事件

触摸板和鼠标行为相反（向上滚动是降低音量），不清楚要怎么处理

2024-07-31 02:27 UTC, NieR4ever commented on app/shared/video-player/src/desktopMain/kotlin/ui/VideoPlayer.desktop.kt
> +        player.audio().setVolume(volume.times(200).roundToInt())
需要改回100吗

2024-07-31 04:13 UTC, NieR4ever commented
新新效果图：
<img width="843" alt="Snipaste_2024-07-31_12-01-48" src="https://github.com/user-attachments/assets/e0ded085-60d2-4c08-a545-c88a37be6115">
<img width="843" alt="Snipaste_2024-07-31_12-02-08" src="https://github.com/user-attachments/assets/f43f4f75-b06a-4a99-9af4-9dd79db3c7da">

2024-07-31 07:07 UTC, Him188 commented
新版好看

2024-07-31 08:39 UTC, NieR4ever commented
效果预览
https://github.com/user-attachments/assets/98237a9f-e063-4f5e-b0c3-52e163e2550d

2024-07-31 08:39 UTC, NieR4ever commented
https://github.com/user-attachments/assets/32896f86-64da-4115-95b4-6a5ef9f525f3

2024-07-31 08:45 UTC, Him188 commented on app/shared/video-player/src/desktopMain/kotlin/ui/VideoPlayer.desktop.kt
> +        player.audio().setVolume(volume.times(200).roundToInt())
ok，那就200

2024-07-31 08:46 UTC, Him188 commented on app/shared/video-player/src/desktopMain/kotlin/ui/VideoPlayer.desktop.kt
> +        player.audio().setVolume(volume.times(200).roundToInt())
哦，应该把那个进度条改成能处理到200

2024-07-31 08:46 UTC, Him188 commented on app/shared/video-player/src/desktopMain/kotlin/ui/VideoPlayer.desktop.kt
> +        player.audio().setVolume(volume.times(200).roundToInt())
200应该是增益吧，增益会不会有音质损失？

2024-07-31 08:55 UTC, NieR4ever commented on app/shared/video-player/src/desktopMain/kotlin/ui/VideoPlayer.desktop.kt
> +        player.audio().setVolume(volume.times(200).roundToInt())
可能会有

2024-07-31 08:56 UTC, Him188 commented
> 触摸板和鼠标行为相反（向上滚动是降低音量）

Compose 应该会处理这个行为然后已经给你反向好了吧，你实际测试过吗

2024-07-31 09:42 UTC, NieR4ever commented
> > 触摸板和鼠标行为相反（向上滚动是降低音量）
> 
> Compose 应该会处理这个行为然后已经给你反向好了吧，你实际测试过吗

测试过了，确实是相反的

2024-08-02 15:32 UTC, NeKoOuO commented
一般拖動條不是會有一個像是圓的把手 是不是加一下比較好

2024-08-02 15:50 UTC, Him188 commented
> 一般拖動條不是會有一個像是圓的把手 是不是加一下比較好

那个我刻意让他删掉的, 我个人感觉那个手柄有点怪, 感觉等 compose 1.7.0 用那个一条线的手柄*可能*会好一点

2024-08-02 15:55 UTC, Him188 commented on app/shared/video-player/src/desktopMain/kotlin/ui/VideoPlayer.desktop.kt
> +        player.audio().setVolume(volume.times(200).roundToInt())
有损耗的话, 我觉得要把那个进度条改成最大值为 200 比较好. 至少不能是目前的初始状态显示 50, 但实际上已经是不损耗音量的 100.

但这样的话, 我们可能还需要为进度条实现简单吸附到 100 的功能, 否则比较难调到不影响音质的最大音量. 

所以我觉得可以先最大 100, 后面再支持增益

2024-08-04 04:50 UTC, Him188 requested changes

2024-08-04 04:50 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +                                    text = volume.times(200).roundToInt().toString(),
应当是 volume 能返回 `0~2.0` 范围

2024-08-04 07:25 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/guesture/VideoGestureHost.kt
> +                    }.ifThen(family.scrollForVolume) {
```suggestion
                    }.ifThen(family.scrollForVolume && playerState !is SupportsAudi) {
```

2024-08-04 07:25 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/guesture/VideoGestureHost.kt
> +                                    indicatorState.showVolumeRange(playerState.volume.value / 2)
这确实是一个问题

在这里硬编码 / 2 感觉不是很好, 我觉得可以给 VolumnManager 增加一个 `maxValue`, VLCJ 实现为 2

2024-08-04 07:25 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +        }
是不是忘了取消 alwaysOn?

2024-08-04 07:25 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +        }
```kotlin
LaunchedEffect {    
   snapshotFlow { isHovered }.collect {
}
```

2024-08-04 07:25 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +        interactionSource: MutableInteractionSource = remember { MutableInteractionSource() },
这个有用么

2024-08-04 07:25 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +                    background(aniColorScheme().surface.copy(alpha = .1f))
这个没起作用吧, 因为下面会 popup

2024-08-04 07:25 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +                .clip(CircleShape)
这个看起来没起作用, 可以删除

2024-08-04 07:25 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +                                    modifier = modifier.padding(8.dp),
```suggestion
                                    modifier = Modifier.padding(8.dp),
```

2024-08-04 07:25 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +                                        inactiveTrackColor = aniDarkColorTheme().onSurface,
```suggestion
                                        inactiveTrackColor = MaterialTheme.colorScheme.onSurface,
```

让外部 (VideoScaffold) 去指定 dark

2024-08-04 07:25 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +                                    valueRange = 0f..2f,
2f 改成用参数提供 (改成 AudioManager.maxValue)

2024-08-04 07:25 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +                        .background(aniColorScheme().surface),
```suggestion
                        .background(MaterialTheme.colorScheme.surface),
```

这种情况下实际上应该把 Box 换为 Surface, Surface 自带 surface color

2024-08-04 08:02 UTC, NieR4ever commented on app/shared/video-player/src/commonMain/kotlin/ui/guesture/VideoGestureHost.kt
> +                    }.ifThen(family.scrollForVolume) {
会使playerState无法找到引用
![image](https://github.com/user-attachments/assets/b73b0931-9cd5-435b-a7e4-0fdd64517048)

2024-08-04 09:12 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/guesture/VideoGestureHost.kt
> +                    }.ifThen(family.scrollForVolume) {
里面的不删除

2024-08-05 05:31 UTC, Him188 approved these changes

2024-08-05 05:32 UTC, Him188 commented
后面可以再加个用音量上下键增减音量 (一次 5% 或者 10%)

2024-08-05 05:39 UTC, Him188 commented on app/shared/video-player/src/desktopMain/kotlin/ui/VideoPlayer.desktop.kt
> +        player.audio().setVolume(volume.times(100).roundToInt())
可以尝试把些都包装到 player.submit 跑, 看能不能解决

2024-08-05 09:21 UTC, Him188 approved these changes

2024-08-05 09:21 UTC, merged