跳过oped
open-ani/ani pull request #708
Opened 2024-08-06 05:10 UTC by NieR4ever

resolve #700 
----
目前只能跳过desktop端有章节的bt资源，`跳过oped`这个功能名称范围可能太大了

2024-08-06 06:46 UTC, Him188 requested changes

2024-08-06 06:46 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/app/AppSettingsTab.kt
> +                title = { Text("跳过oped") },
```suggestion
                title = { Text("自动跳过 OP 和 ED") },
```
- 中英文之间有空格
- OP 是缩写, 应当大写
- OP/ED 是两个词不应该写到一起

2024-08-06 06:46 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/models/preference/VideoScaffoldConfig.kt
> +     * 跳过oped
```suggestion
     * 自动跳过 OP 和 ED
```

2024-08-06 06:46 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/models/preference/VideoScaffoldConfig.kt
> +    val skipOped: Boolean = false,
```suggestion
    val autoSkipOpEd: Boolean = false, 
```

2024-08-06 06:46 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +    var cancelSkipOped: Boolean
这应该是一个独立的

`PlayerFloatingTipsState`, EpisodeVM 只能组装别的 state, 不能承载 state.

2024-08-06 06:46 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +                    if (!enabled || episodeSelectorState.currentIndex == 0) return@collectLatest
能不能加点 unit testing?

2024-08-06 06:46 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +                                }
我 expect 这个算法部分一定是要 unit test 的

2024-08-06 06:46 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +                    .background(MaterialTheme.colorScheme.surface.copy(alpha = .3f)),
```sugggestion
                    .background(MaterialTheme.colorScheme.surface),
```
保证对比度

2024-08-06 06:46 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +        ) {
AnimatedVisibilty 应该在外面考虑

2024-08-06 06:46 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +                contentAlignment = Alignment.Center,
```suggestion
                contentAlignment = Alignment.CenterStart,
```
看起来这个地方应该用 CenterStart

2024-08-06 06:46 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +                            text = "即将跳过oped",
```suggestion
                            text = "即将跳过 OP 或 ED",
```

2024-08-06 06:46 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/PlayerControllerBar.kt
> +                            modifier = Modifier.padding(start = 8.dp),
没有 verticalPadding? 可以参考 M3 slider label 的 padding?

2024-08-08 02:00 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +        playerFloatingTipsState.skipOpEd = true // 切换ep后重置跳过oped
`switchEpisode` 在后台运行, 而 `skipOpEd` 是 compose State, 这会导致随机 crash

2024-08-08 02:00 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +                    //未启用 或 第一集时返回
```suggestion
                    // 未启用 或 第一集时返回
```

2024-08-08 02:00 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +                    if (!enabled || episodeSelectorState.currentIndex == 0) return@collectLatest
这是不是在阅读 compose state? 是的话必须在 Dispatchers.Main 进行
有没有不需要阅读 state 的方法?

2024-08-08 02:00 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +                            playerState.videoProperties.map { it?.durationMillis }.debounce(5000),
5000 是不是太多了, 跳过 op 的提示比较时间敏感

2024-08-08 02:00 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    fun autoSkipOpEd(pos: Long, max: Long?, chapters: List<Chapter>, onSeek: (Long) -> Unit) {
```suggestion
    fun calculateTargetTime(pos: Long, max: Long?, chapters: List<Chapter>): Long? {
```

2024-08-08 02:00 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +        chapters.forEach {
```suggestion
        return chapters.firstNotNullOfOrNull {
```

2024-08-08 02:00 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    fun autoSkipOpEd(pos: Long, max: Long?, chapters: List<Chapter>, onSeek: (Long) -> Unit) {
max 不应当能是 null

2024-08-08 02:00 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    fun autoSkipOpEd(pos: Long, max: Long?, chapters: List<Chapter>, onSeek: (Long) -> Unit) {
chapters 可能要放到第一个, 一般习惯是较大的参数放到第一个

2024-08-08 03:32 UTC, Him188 reviewed
我觉得调用 autoSkipOpEd 用 onSeek 回调处理不好, 这会导致 onSeek 被调用多次

2024-08-08 03:32 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerFloatingTipsStateTest.kt
> +    fun `pos before op 10s when 12 minute`() {
```suggestion
    @Test
    fun `12 minutes - pos before op 10s`() {
```
我觉得这种命名可能比较容易分辨

这样我能清晰看到你为 `12 minutes` 类型写了几个测试

2024-08-08 03:32 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerFloatingTipsStateTest.kt
> +    val chapters = listOf(
private

应该有 warning 吧

2024-08-08 03:32 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    var leftBottomTipsVisible: Boolean by mutableStateOf(false)
```suggestion
    /**
      * 显示 "即将跳过 OP/ED" 的提示, 通常在播放器左下角
      */
    var showSkipOpEd: Boolean by mutableStateOf(false)
        private set
```

2024-08-08 03:32 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    fun cancelSkipOpEd() {
加个注释

2024-08-08 03:32 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    var skipOpEd: Boolean by mutableStateOf(true)
```suggestion
    var enableSkipOpEd: Boolean by mutableStateOf(true)
```

加一行简单注释说明下有什么作用

2024-08-08 03:32 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +            }
```suggestion
            val matched = when {
                max > 20 * 60 * 1000 -> it.durationMillis in 85_000..95_000
                max > 10 * 60 * 1000 -> it.durationMillis in 55_000..65_000
                else -> false
            }
```

这种简单语句一般使用这种紧凑格式来省空间

2024-08-08 03:32 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +                    it.durationMillis in 85_000..95_000
在一个很大的 lambda 中, 不能适合 it, 要给 it 命名, 保证逻辑清晰

实际上只有 1-2 行这种量级的才比较适合用 it

2024-08-10 08:14 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    fun calculateTargetTime(chapters: List<Chapter>, pos: Long, max: Long): Long? {
不应该依赖 max, 应该依赖一个 OpEdLength, 这样你也不用在 test 的时候分两种情况了, 因为判断时间的逻辑已经解耦了

Idiomatic Kotlin:

```kotlin
fun interface OpEdLength {
    fun isOpEdChapter(chapterLength: Duration): Boolean

    companion object {
        private val Short = OpEdLength { it in 85.seconds..85.seconds }
        private val Normal = OpEdLength { it in 55.seconds..65.seconds }

        fun fromVideoLengthOrNull(length: Duration): OpEdLength? {
            return when {
                length > 20.minutes -> Normal
                length > 10.minutes -> Short
                else -> null
            }
        }
    }
}
```

2024-08-10 08:14 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    var enableSkipOpEd: Boolean by mutableStateOf(true)
如果在出现提示后, 用户手动跳转到了另一个地方, 需要取消跳过

2024-08-10 08:14 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    var enableSkipOpEd: Boolean by mutableStateOf(true)
目前这个设计可能不好, 在到达 OP 章节之前, 也是可以调用 `cancelSkipOpEd` 并禁止跳过的. 实际上不应该这样. 

应该只有在到达章节后才能允许 cancel. 需要反映在测试中

2024-08-10 08:14 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    fun calculateTargetTime(chapters: List<Chapter>, pos: Long, max: Long): Long? {
感觉这个名字还是不好, 因为我看到这个名字, 会 expect 它只计算东西并返回, 实际上它有副作用 `showSkipOpEd = true`.

我有个想法:

```kotlin
@Stable
class PlayerSkipOpEdState(
    chapters: State<List<Chapter>>
    private val onSkip: (targetMillis: Long) -> Unit,
    videoLength: State<Duration>,
) {
    private val chapters by chapters
    private val videoLength by videoLength
    private var currentOp: Chapter?

    fun update(currentPos: Long) {
          ...

              onSkip(target)
    }  
}
```

这样比较符合逻辑. 也可以单元测试在遇到章节后, 切换 ep 的情况 (因为切换 ep 时, 章节信息也会变)

2024-08-10 08:15 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    fun calculateTargetTime(chapters: List<Chapter>, pos: Long, max: Long): Long? {
目前的 `enableSkipOpEd` 我感觉非常容易在切换 ep 时坏掉, 而且很难 unit test.

2024-08-11 00:22 UTC, NieR4ever commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    fun calculateTargetTime(chapters: List<Chapter>, pos: Long, max: Long): Long? {
不清楚currentOp的作用

2024-08-11 04:08 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    fun calculateTargetTime(chapters: List<Chapter>, pos: Long, max: Long): Long? {
update遇到章节时更新

2024-08-11 04:25 UTC, NieR4ever commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    fun calculateTargetTime(chapters: List<Chapter>, pos: Long, max: Long): Long? {
那它叫currentChapter可能更合适

2024-08-11 08:10 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerFloatingTipsState.kt
> +    fun calculateTargetTime(chapters: List<Chapter>, pos: Long, max: Long): Long? {
确实

2024-08-12 06:50 UTC, NieR4ever commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerFloatingTipsStateTest.kt
> +
没op感觉没必要测试

2024-08-12 10:22 UTC, Him188 requested changes

2024-08-12 10:22 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerSkipOpEdState.kt
> +    private fun requestShowSkipTips(requester: Any, show: Boolean) {
这个逻辑不对吧, 不能有多个 request

skip 也是, skip 不应但是 request

我比较期望的是每秒调用 update, 当遇到 op 时就更新 `var currentChapter`. 跳过成功后 set currentChapter = null.
```kotlin
class CurrentChapter(val chapter: Chapter, var skipped: Boolean)
```
点击跳过时更新 `skipped` 属性, 后面就不执行操作

2024-08-12 10:22 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerSkipOpEdStateTest.kt
> +class PlayerSkipOpEdStateTest {
我觉得应该是没必要分别测试 12min/24min 的, 只测试 24 的就够了. 因为解耦出来 `OpEdLength` 后, 这些时长仅仅是参数而已了

2024-08-12 10:22 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerSkipOpEdStateTest.kt
> +package ui.subject.episode.video
```suggestion
package me.him188.ani.app.ui.subject.episode.video
```

2024-08-12 10:22 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerSkipOpEdStateTest.kt
> +    class `24 minutes - opChapterOnChapter2` : NeedTest() {
why `2`?

2024-08-12 10:59 UTC, NieR4ever commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerSkipOpEdStateTest.kt
> +    class `24 minutes - opChapterOnChapter2` : NeedTest() {
op章节在第二个章节的意思

2024-08-13 11:00 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerSkipOpEdState.kt
> +        }
应该先检查 `currentChapter == null` 再 find, 避免无用的计算

2024-08-13 11:00 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerSkipOpEdState.kt
> +        opEdChapters.map { it.chapter }.find { it.offsetMillis in currentPos - 1000..currentPos }?.run {
```suggestion
        opEdChapters.asSequence().map { it.chapter }.find { it.offsetMillis in currentPos - 1000..currentPos }?.run {
```

list 的 map 会构造新的 list, 会有一些内存影响, 用 sequence 就没问题

2024-08-13 11:00 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerSkipOpEdState.kt
> +        opEdChapters.map { it.chapter }.find { it.offsetMillis in currentPos - 1000..currentPos }?.run {
应当只考虑 current 吧

2024-08-13 11:00 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerSkipOpEdState.kt
> +                currentChapter = it.copy()
copy doesn't seem right, 见我其他 comment 描述的期望行为

2024-08-13 11:00 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerSkipOpEdState.kt
> +        }.map { CurrentChapter(chapter = it, true) }
确实, OP 只能跳过一次. 如果跳过 OP 后, 它又把进度拖回来, 不能重复跳过. 

应当默认 skipped 是 false 吧, cancel 或者跳过之后设置为 true

需要增加这个的单元测试

2024-08-13 11:00 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerSkipOpEdStateTest.kt
> +    abstract fun `after show tips user seek to other place`()
这些抽象是没有必要的, subclass 需要什么测试自己就添加什么就好了

2024-08-13 11:00 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerSkipOpEdStateTest.kt
> +        override fun `cancel before op 3s then play to op`() {
missing `@Test`

2024-08-13 11:00 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerSkipOpEdStateTest.kt
> +        override fun `cancel before op 6s then play to op`() {
missing `@Test`

2024-08-13 11:00 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerSkipOpEdStateTest.kt
> +        }
这看起来更复杂了, 建议总是在单个 test 内 `val state = `

2024-08-13 11:00 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerSkipOpEdStateTest.kt
> +    open val noOpChapter: List<Chapter> = emptyList()
没有这些抽象的意义吧

2024-08-13 11:00 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerSkipOpEdStateTest.kt
> +abstract class NeedTest {
看起来这整个 class 都是没有必要的

2024-08-13 11:00 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerSkipOpEdStateTest.kt
> +            state.update(16_000L)
这回退了一毫秒是有什么讲究吗

2024-08-13 11:00 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerSkipOpEdStateTest.kt
> +class PlayerSkipOpEdStateTest {
增加一下记忆跳过 OP 的情况:

- 成功自动跳过 OP 后, 用户又回到 OP 开头, 此时不能触发自动跳过
- 用户取消跳过后, 用户又回到 OP 开头, 此时不能触发自动跳过
- 显示即将跳过 OP 的弹窗, 用户立即拖到别的地方, 应当取消跳过并且记忆操作. 当用户又回到 OP 开头, 此时不能触发自动跳过

可以把这三句话描述注释到 case 上面方便理解

2024-08-15 14:33 UTC, NieR4ever commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerSkipOpEdState.kt
> +        }
似乎是不能先检查 `currentChapter == null`的，无论 currentChapter 是否为 null 都需要检测 `currentPos - 1000..currentPos + 5000` 这个区间中是否有章节，为了控制跳过提示只在该区间内显示

2024-08-16 15:18 UTC, Him188 approved these changes

2024-08-16 15:22 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerSkipOpEdStateTest.kt
> +            // 回到显示跳过提示
再加两个 case: 到达 OP 前 3 秒导致 showSkipTips = true, 然后滑动到 OP 之中或者之后, 都应当取消跳过. 并且下次再滑回来这个OP 章节前 3 秒的时候, 不显示 tips

2024-08-16 15:23 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/PlayerSkipOpEdState.kt
> +        }
ok, 我不是很懂细节, 但只要 test 都过了就 LGTM

2024-08-16 15:24 UTC, Him188 commented
然后 mrege 一下 master

2024-08-17 00:37 UTC, NieR4ever commented
![PixPin_2024-08-17_08-34-56](https://github.com/user-attachments/assets/c4cf8429-9369-41df-820d-3f62ae00ca53)
![PixPin_2024-08-17_08-35-55](https://github.com/user-attachments/assets/965e109b-0f51-49c7-9ff5-214d23385c2a)

2024-08-17 08:36 UTC, Him188 approved these changes

2024-08-17 08:38 UTC, merged

2024-08-17 08:38 UTC, Him188 commented on app/shared/src/commonTest/kotlin/ui/subject/episode/video/PlayerFloatingTipsStateTest.kt
> +
ok