Deskop updater (only windows implement)
open-ani/ani pull request #710
Opened 2024-08-06 13:58 UTC by hacbit

更新了windows平台Ani的更新服务，本地测试release没问题（

2024-08-06 14:24 UTC, NeKoOuO commented
這是需要自己下載 updater 到本地嗎

2024-08-06 14:29 UTC, hacbit commented
> 這是需要自己下載 updater 到本地嗎

按照him的说法，应该是会放在 `app\desktop\appResources\windows-x64` 再进行打包，不需要手动下载

2024-08-06 14:34 UTC, NeKoOuO commented
看起來能夠直接解決這個問題 #599
#321 然後這個或許也可以加一下O_o

2024-08-06 14:38 UTC, hacbit commented
> 看起來能夠直接解決這個問題 #599 #321 然後這個或許也可以加一下O_o

#599 的问题应该能够解决，不过 #321 的增量更新还没实现。目前只是应him要求先实现了全量更新

2024-08-08 01:51 UTC, Him188 requested changes

2024-08-08 01:51 UTC, Him188 commented on app/desktop/src/main/kotlin/AniDesktop.kt
> +            logger.error(it) { "Failed to update installer" }
```suggestion
            logger.error(it) { "Failed to delete update installer" }
```

2024-08-08 01:51 UTC, Him188 commented on app/shared/src/desktopMain/kotlin/tools/update/DesktopUpdateInstaller.kt
> +            logger.info { "'ani_update.exe' not found. Fallback to manual update" }
```suggestion
            logger.error { "'ani_update.exe' not found. Fallback to manual update" }
```

2024-08-08 01:51 UTC, Him188 commented on app/shared/src/desktopMain/kotlin/tools/update/DesktopUpdateInstaller.kt
> +        val updateExecutable = appDir.resolve("app/resources/ani_update.exe")
这是不正确的路径

参考:
- me.him188.ani.app.desktop.TestDiscoveryDirectoryProvider
- me.him188.ani.app.desktop.ComposeResourcesDiscoveryDirectoryProvider

2024-08-08 01:51 UTC, Him188 commented
把 exe 也放进来吧

2024-08-08 02:01 UTC, hacbit commented on app/shared/src/desktopMain/kotlin/tools/update/DesktopUpdateInstaller.kt
> +        val updateExecutable = appDir.resolve("app/resources/ani_update.exe")
看起来我需要使用 `System.getProperty("compose.application.resources.dir")` 来获取resources文件夹地址？

2024-08-08 02:05 UTC, Him188 commented on app/shared/src/desktopMain/kotlin/tools/update/DesktopUpdateInstaller.kt
> +        val updateExecutable = appDir.resolve("app/resources/ani_update.exe")
是的

2024-08-08 02:27 UTC, hacbit commented
> 把 exe 也放进来吧

放进来了

2024-08-08 02:40 UTC, hacbit commented on app/shared/src/desktopMain/kotlin/tools/update/DesktopUpdateInstaller.kt
> +            logger.info { "'ani_update.exe' not found. Fallback to manual update" }
error似乎需要一个参数，参考AniDesktop是把catch的错误信息传给logger.error 这里需要怎么获取？可能需要改回 info ？
另外在前面Ani.exe没有找到时输出的错误也是使用 info 而不是 error

2024-08-10 07:33 UTC, Him188 approved these changes
需要测试

2024-08-11 17:17 UTC, Him188 commented
@StageGuard @NieR4ever 有空人工测试一下吗

1. 下载 https://github.com/open-ani/ani/suites/26932904125/artifacts/1788611994
2. 解压后打开
3. 自动更新应该会提示有更新到 3.6.0, 点下载然后更新
4. 期望自动更新成功并启动 3.6.0

2024-08-11 17:43 UTC, hacbit commented
> @StageGuard @NieR4ever 有空人工测试一下吗
> 
> 1. 下载 https://github.com/open-ani/ani/suites/26932904125/artifacts/1788611994
> 2. 解压后打开
> 3. 自动更新应该会提示有更新到 3.6.0, 点下载然后更新
> 4. 期望自动更新成功并启动 3.6.0

不过预期应该是Ani.exe 同目录下会残留 ani_update.exe （因为Ani启动删除 ani_update 的逻辑应该还没同步到 3.6.0）（起码我这边测试更新到3.6.0是这样）

2024-08-11 17:48 UTC, Him188 commented
删除是可有可无的

2024-08-11 23:40 UTC, NieR4ever commented
符合预期
重启过程中从update窗口关闭到ani窗口打开，体感需要2秒左右，可能需要在update程序中提示一下正在启动ani

2024-08-12 04:43 UTC, hacbit commented
> 符合预期 重启过程中从update窗口关闭到ani窗口打开，体感需要2秒左右，可能需要在update程序中提示一下正在启动ani

其实在最后是有一行等待Ani启动的提示的，不过有点小（。

2024-08-12 04:46 UTC, StageGuard commented
符合预期，但是

![image](https://github.com/user-attachments/assets/8dcd51d8-f47d-4b7d-b6d1-2d4978af67d8)

2024-08-12 04:49 UTC, hacbit commented
> 符合预期，但是颜色字符在 cmd 不支持
> 
> ![image](https://private-user-images.githubusercontent.com/45701251/356937393-8dcd51d8-f47d-4b7d-b6d1-2d4978af67d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MzgzMjQsIm5iZiI6MTcyMzQzODAyNCwicGF0aCI6Ii80NTcwMTI1MS8zNTY5MzczOTMtOGRjZDUxZDgtZjQ3ZC00YjdkLWI2ZDEtMmQ0OTc4YWY2N2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA0NDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MmE4NjE0MmZlNTdkNjEzYWYxNTI2YTcyMWY3YmY1Nzc1ZTY4OWM4ZmU2MmQ2OWQ0NGRiMGFlOTExYTMwZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eEROqLPb4tsHSf89SzboL_1NUwx7S0j00A4Y8tasSUM)

终端本身不支持我也没办法（。不过我可以搓一个轻量的GUI来显示有颜色的输出（）

2024-08-12 04:52 UTC, StageGuard commented
> 终端本身不支持我也没办法（。不过我可以搓一个轻量的GUI来显示有颜色的输出（）

也不是什么大的问题，就这样也可以

2024-08-12 06:00 UTC, merged