fix danmaku button
open-ani/ani pull request #716
Opened 2024-08-07 23:33 UTC by NieR4ever

fix #704

2024-08-08 01:46 UTC, Him188 requested changes
这样的话我们就有两个地方都有 danmakuEnabled 属性. 我不觉得这是正确的. 

弹幕开关设置期望是要持久化的, 关闭之后未来就一直关闭了. 我觉得应当修复 VideoDanmakuStateImpl

2024-08-08 01:46 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +        danmaku.setEnabled(true)
这会覆盖用户设置, 导致无法记忆弹幕开关状态

2024-08-11 06:37 UTC, NieR4ever commented
> 这样的话我们就有两个地方都有 danmakuEnabled 属性. 我不觉得这是正确的.
> 
> 弹幕开关设置期望是要持久化的, 关闭之后未来就一直关闭了. 我觉得应当修复 VideoDanmakuStateImpl

我在设置里没找到弹幕开关，这个设置项在别的地方吗

2024-08-11 07:06 UTC, Him188 commented
> 我在设置里没找到弹幕开关

就是播放器的那个开关，不是在单独设置页里

2024-08-11 14:14 UTC, Him188 reviewed
懂你的问题是什么了, 那似乎目前还没有实现持久化这个开关, 那就不用管

2024-08-11 14:14 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +
```suggestion
```

2024-08-11 14:14 UTC, Him188 approved these changes

2024-08-11 15:01 UTC, merged