修复滑动手势导致进度条位置不正确
open-ani/ani pull request #732
Opened 2024-08-09 12:43 UTC by NieR4ever

fix #720

2024-08-10 07:35 UTC, Him188 commented
fix conflicts?

2024-08-10 07:38 UTC, Him188 commented
好了之后 request 我

2024-08-11 17:20 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/MediaProgressSlider.kt
> +                if (state.isPreviewing && !enabled) {
enable 跟这个问题没关系吧

2024-08-11 18:13 UTC, Him188 reviewed
得加点测试

可以试试普通的 runComposeStateTest 能不能做到 ` = runComposeStateTest {`
通过改变 `currentPositionMillis` 可以模拟视频播放

明天我补全其他 UI test case 后看看这个适不适合做 UI test (理想情况下要有, 可以模拟滑动手势, 给人以最大的信心它能工作)

2024-08-11 23:51 UTC, NieR4ever commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/MediaProgressSlider.kt
> +                if (state.isPreviewing && !enabled) {
这个是删除 previewRequests 的附带bug，原来预期只在仅在 detached slider 上显示，删除之后在controller bar上也会显示
```kt
    private val previewRequests = SnapshotStateList<Any>()

    fun setRequestPreview(requester: Any, isPreview: Boolean) {
        if (isPreview) {
            previewRequests.add(requester)
        } else {
            previewRequests.remove(requester)
        }

        if (previewRequests.isEmpty()) {
            finishPreview()
        }
    }
```

2024-08-12 02:35 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/progress/MediaProgressSlider.kt
> +                if (state.isPreviewing && !enabled) {
这个enabled是不正确的，enabled本身不是这个意思，不能制造副作用。需要用别的方式实现

2024-08-12 03:56 UTC, Him188 requested changes

2024-08-12 03:56 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/progress/MediaProgressSliderStateTest.kt
> +        val chapters = object : ImmutableList<Chapter> {
```suggestion
        val chapters = persistentListOf()
```

2024-08-12 03:56 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/progress/MediaProgressSliderStateTest.kt
> +            },
给 parameter 加下名字, 这种 lambda 比较多的情况都建议加

![image](https://github.com/user-attachments/assets/79b72a9a-90a5-4d6f-a1d5-ad863e7e0878)

光标在 `(` 处 alt enter

2024-08-12 03:56 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/progress/MediaProgressSliderStateTest.kt
> +        scope.launch {
```suggestion
        launch {
```

test 是单线程的, 主线程 Main 和当前协程是一个单线程调度器 `TestDispatcher` 跑的

2024-08-12 03:56 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/progress/MediaProgressSliderStateTest.kt
> +        }
这样 launch 的话会导致不确定吧, 我觉得是没有必要 launch 的

2024-08-12 03:56 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/progress/MediaProgressSliderStateTest.kt
> +        delay(5.seconds)
test (TestDispatcher) 中这个不会有任何效果

可以把上面 launch 删掉, 直接在这里修改时间. 然后调用 `takeSnapshot()`, 可以让所有 derivedState 重新计算.

2024-08-12 16:31 UTC, Him188 reviewed
最好再加上一个 case:

- preview, 进度更新, finish preview 之后, displayPositionRatio 应该是什么?

2024-08-12 16:31 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/progress/MediaProgressSliderStateTest.kt
> +package ui.progress
```suggestion
package me.him188.ani.app.ui.progress
```

2024-08-12 16:31 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/progress/MediaProgressSliderStateTest.kt
> +import org.junit.jupiter.api.Test
use kotlin API

2024-08-12 16:31 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/progress/MediaProgressSliderStateTest.kt
> +        assertEquals(0.5f, state.displayPositionRatio)
```suggestion
        state.previewPositionRatio(0.5f)
        state.finishPreview()
        takeSnapshot()
        assertEquals(0.5f, state.displayPositionRatio)
```

我感觉这里需要 take 一个, 否则可能有概率有问题

2024-08-12 16:31 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/progress/MediaProgressSliderStateTest.kt
> +    fun testMediaProgressSliderState() = runComposeStateTest {
```suggestion
    fun `preview and finish preview then play`() = runComposeStateTest {
```

2024-08-13 05:56 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/progress/MediaProgressSliderStateTest.kt
> +        assertEquals(0.5f, state.displayPositionRatio)
这是符合预期的吗?

预览结束之后不应当要反应最新的 position, 也就是 `0.55f` 吗

2024-08-13 06:56 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/progress/MediaProgressSliderStateTest.kt
> +        assertEquals(0.5f, state.displayPositionRatio)
懂了, 预览结束会设置 position

2024-08-13 06:57 UTC, merged