allow close MediaCache synchronously and asynchronously
open-ani/ani pull request #734
Opened 2024-08-10 04:06 UTC by StageGuard

为 `MediaCache` 添加一个 `closeBlocking` 方法，调用 `session_t.release_handle`，等待 `torrent_checked_alert` 事件后返回。

see: 
https://www.libtorrent.org/reference-Session.html#remove-torrent
https://www.libtorrent.org/reference-Alerts.html#torrent_removed_alert

2024-08-10 07:11 UTC, Him188 requested changes
逻辑太复杂了, 能不能去掉不等待的 close, 全统一成会等待?

2024-08-10 07:11 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/source/media/MediaCacheManager.kt
> +    }
backgroundScope.async 会导致泄露, `closeAllCachesBlocking` 被 cancel 后, 你启动的 job 不会被 cancel

```suggestion
    suspend fun closeAllCachesBlocking() = supervisorScope {
        for (storage in enabledStorages.first()) {
            for (mediaCache in storage.listFlow.first()) {
                launch { mediaCache.closeBlocking() }
            }
        }
    }
```

2024-08-10 07:11 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/source/media/cache/MediaCache.kt
> +     * 从引擎中关闭此缓存任务, 关闭后不能再开启.
说明此函数不会等

2024-08-10 07:11 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/source/media/DummyMediaCacheEngine.kt
> +    override suspend fun closeBlocking() {
我建议会等的叫 `close`, 不会等的叫 `closeLater`

2024-08-10 07:11 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +        combine(mediaCacheListFromStorages) { lists ->
没必要的 combine

2024-08-10 07:11 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +            lists.asSequence().flatten().map { it.isValid() }.toList().size
不是 filter?

2024-08-10 07:11 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +            lists.asSequence().flatten().map { it.isValid() }.toList().size
```suggestion
            lists.asSequence().flatten().map { it.isValid() }.count()
```

2024-08-10 07:11 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +                                    toaster.toast("已复制。")
```suggestion
                                    toaster.toast("已复制")
```

2024-08-10 07:11 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +                                    toaster.toast("已复制。")
无关修改单独直接 commit 到 master, 否则 PR 合并后发现 bug 了 revert PR 时会导致这个修改也丢失

2024-08-10 07:11 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +                                    toaster.toast("已关闭所有缓存任务。")
```suggestion
                                    toaster.toast("已关闭所有缓存任务")
```
我相信 toast 语境是无需句号的

2024-08-10 07:11 UTC, Him188 commented on torrent/api/src/commonMain/kotlin/api/files/TorrentFileEntry.kt
> +        private inline fun preClose() {
no need to inline

2024-08-10 07:11 UTC, Him188 commented on torrent/api/src/commonMain/kotlin/api/files/TorrentFileEntry.kt
> +        private inline fun preClose() {
confusing naming


close, preClose, closeImpl, closeBlocking, closeBlockingImpl

2024-08-10 07:11 UTC, Him188 commented on torrent/api/src/commonMain/kotlin/api/files/TorrentFileEntry.kt
> +        final override suspend fun closeBlocking() {
线程不安全

2024-08-10 07:11 UTC, Him188 commented on torrent/api/src/commonMain/kotlin/api/files/TorrentFileEntry.kt
> +            if (closed) return closingDeferred.await()
这个行为比较奇怪

2024-08-10 07:11 UTC, Him188 commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentTorrentDownloader.jvm.kt
> +                runBlocking(Dispatchers.IO) {
not cancellable

Use `runInterrpiable`

2024-08-10 07:11 UTC, Him188 commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentDownloadSession.kt
> +            closeBlockingDeferred?.await()
我觉得应当做一个 timeout 5 秒, 我很担心事件会收不到

2024-08-10 07:20 UTC, StageGuard commented
> 逻辑太复杂了, 能不能去掉不等待的 close, 全统一成会等待?

我觉得可以，本来是想这么做，但是想了一下改了 close() 的行为会让目前某些调用这个函数的场景发生其他变化。

2024-08-10 07:21 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +            lists.asSequence().flatten().map { it.isValid() }.toList().size
脑子不清醒了

2024-08-10 07:29 UTC, Him188 commented
> 但是想了一下改了 close() 的行为会让目前某些调用这个函数的场景发生其他变化。

review 一遍全都改了吧, 我简单想了一下应该问题不大

2024-08-10 08:11 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +        combine(mediaCacheListFromStorages) { lists ->
copy from `CacheManagementPage.accumulatedList`

2024-08-10 08:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +        combine(mediaCacheListFromStorages) { lists ->
改一下, combine 会 launch 协程, 还是有点性能 implication 的

2024-08-10 08:41 UTC, StageGuard commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentDownloadSession.kt
> +            closeBlockingDeferred?.await()
应当由 caller 来等待超时

2024-08-10 09:04 UTC, Him188 commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentDownloadSession.kt
> +            closeBlockingDeferred?.await()
应当由你来等待, 因为这个属于是你的 bug

2024-08-10 09:09 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +        combine(mediaCacheListFromStorages) { lists ->
只会 launch 1-2 个协程，应该没问题，而且不 combine 我也不知道怎么写

2024-08-10 10:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +        combine(mediaCacheListFromStorages) { lists ->
```suggestion
        mediaCacheListFromStorages.map { lists ->
```

2024-08-10 10:21 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +                                    toaster.toast("已复制。")
did you resolve this

2024-08-10 10:27 UTC, Him188 submitted a review, later dismissed

2024-08-10 10:27 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/source/media/cache/MediaCache.kt
> +        println("stop")
```suggestion
    override suspend fun close() {
        println("close")
```

2024-08-10 10:27 UTC, Him188 commented on app/shared/video-player/src/androidMain/kotlin/PlayerState.android.kt
> +                }
```suggestion
                backgroundScope.launch(NonCancellable) {
                    data.close()
                }
```

2024-08-10 10:27 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/state/PlayerState.kt
> +                }
```suggestion
                backgroundScope.launch(NonCancellable) {
                    data.close()
                }
```

2024-08-10 10:27 UTC, Him188 commented on app/shared/video-player/src/desktopMain/kotlin/ui/VideoPlayer.desktop.kt
> +                }
```suggestion
                backgroundScope.launch(NonCancellable) {
                    data.close()
                }
```

2024-08-10 10:27 UTC, Him188 commented on torrent/api/src/commonMain/kotlin/api/files/TorrentFileEntry.kt
> +                closed = true
not thread safe

需要再次检查 `if (closed) return`

2024-08-10 10:27 UTC, Him188 commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentDownloadSession.kt
> +            withTimeout(30000L) {
用得着这么久吗

2024-08-10 10:27 UTC, Him188 commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentDownloadSession.kt
> +        closeBlockingDeferred = currentDeferred
not thread safe

2024-08-10 10:27 UTC, Him188 commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentDownloadSession.kt
> +            closeBlockingDeferred?.await()
missing timeout

2024-08-10 10:27 UTC, Him188 commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentDownloadSession.kt
> +    private var closeBlockingDeferred: CompletableDeferred<Unit>? = null
```suggestion
    private val closeBlockingDeferred: CompletableDeferred<Unit> by lazy 
```

2024-08-10 12:38 UTC, StageGuard commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentDownloadSession.kt
> +            closeBlockingDeferred?.await()
下面 timeout 会强制 complete

2024-08-10 13:03 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +        combine(mediaCacheListFromStorages) { lists ->
无论怎样都要 combine，这里去掉了那也会在下面的 debugInfoFlow 中 combine。 mediaCacheListFromStorages 这个 list 必须马上执行终端操作（sum 或者 fold），which is suspended.

2024-08-10 14:54 UTC, Him188 requested changes

2024-08-10 14:54 UTC, Him188 commented on torrent/api/src/commonMain/kotlin/api/TorrentDownloadSession.kt
> +    suspend fun getName(): String
为什么要加 getName, 之前没 name 不是能跑么

2024-08-10 14:54 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/AboutTab.kt
> +        combine(validMediaCacheTasks) { list -> list.sum() },
还是到上面 combine 吧

2024-08-10 14:54 UTC, Him188 commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentTorrentDownloader.jvm.kt
> +            onPostClose = { openSessions.value -= data.data.contentHashCode().toString() },
我怀疑这会出问题

一旦 native release 了, 调用任何接口都会 crash VM

2024-08-10 14:54 UTC, Him188 commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentTorrentDownloader.jvm.kt
> +                        session.getName() == torrentName
what if 在刚刚添加一个磁力链, 此时没网, 磁力链无法解析, 于是没有 name, 那你这个逻辑就坏了

2024-08-10 14:57 UTC, StageGuard commented on torrent/api/src/commonMain/kotlin/api/TorrentDownloadSession.kt
> +    suspend fun getName(): String
1) 多文件的下载任务不能跑
2) 降低复杂度

2024-08-10 14:58 UTC, StageGuard commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentTorrentDownloader.jvm.kt
> +                        session.getName() == torrentName
getName 会 await actualTorrentInfo，getFiles 也是这样的

2024-08-10 16:45 UTC, Him188 commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentTorrentDownloader.jvm.kt
> +                        session.getName() == torrentName
删除并不会使用 files

2024-08-10 16:56 UTC, StageGuard commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentTorrentDownloader.jvm.kt
> +                        session.getName() == torrentName
> 删除并不会使用 files

之前的方法并不可靠。之前使用 torrent 文件名来判断，torrent 名字可能会和 torrent 文件名不相同，并且使用了 getFiles 也会有你说的问题。
目前得知 torrent 任务完成后调用 session.remove_torrent 触发的 alert 才会导致 handle id = 0，尚不清楚刚添加 torrent 并且没网获取 torrent 信息的情况下 handle id 是否有效，如果有效，那这里的逻辑就没什么问题。

2024-08-10 17:05 UTC, Him188 commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentTorrentDownloader.jvm.kt
> +                        session.getName() == torrentName
handle 应该是有效的, 那应该没问题

2024-08-11 12:30 UTC, StageGuard commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentTorrentDownloader.jvm.kt
> +            onPostClose = { openSessions.value -= data.data.contentHashCode().toString() },
那要怎么处理？在 jvm 里判断 closed 属性？

2024-08-11 12:45 UTC, Him188 commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentTorrentDownloader.jvm.kt
> +            onPostClose = { openSessions.value -= data.data.contentHashCode().toString() },
不知道

2024-08-11 13:07 UTC, StageGuard commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentTorrentDownloader.jvm.kt
> +            onPostClose = { openSessions.value -= data.data.contentHashCode().toString() },
我觉得不用判断，我看了一眼 torrent_info_t，所有的接口都会先判断 handle.is_valid，如果没有线程安全问题那就没问题。

2024-08-11 14:03 UTC, Him188 commented on torrent/impl/anitorrent/src/jvmMain/kotlin/AnitorrentTorrentDownloader.jvm.kt
> +            onPostClose = { openSessions.value -= data.data.contentHashCode().toString() },
ok

2024-08-11 23:31 UTC, StageGuard commented
你还没 approve

2024-08-12 02:36 UTC, Him188 approved these changes

2024-08-12 02:36 UTC, merged