[WIP] feat: show all episode in select
open-ani/ani pull request #739
Opened 2024-08-10 23:51 UTC by chivehao

2024-08-11 12:47 UTC, StageGuard commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +fun EpisodeSort(int: BigNum, type: Int): EpisodeSort {
```suggestion
fun EpisodeSort(int: BigNum, type: Int): EpisodeSort {
    return when (type) {
        0 -> EpisodeSort(int)
        1 -> Special("SP$int")
        // ...
    }
```

2024-08-11 12:47 UTC, StageGuard commented on data-sources/ikaros/src/IkarosClient.kt
> +        var ikarosEpisodeGroup = "MAIN";
同样改成 when

2024-08-11 12:59 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +fun EpisodeSort(int: BigNum, type: Int): EpisodeSort {
no int type

2024-08-11 17:24 UTC, Him188 requested changes

2024-08-11 17:24 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +        episodeSort = Special(prefix + int.toString())
这个逻辑应当是特定数据源做的, 不是通用的 EpisodeSort

2024-08-11 18:50 UTC, chivehao commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +        episodeSort = Special(prefix + int.toString())
并不是特定数据源的，
这个需要根据ani的episodetype进行判断，但是因为项目模块的关系，这个类没法导入EpisodeType，EpisdeType里目前就这三个，所以这就只判断了这三个。
而数据源解析剧集序号，一样需要根据EpisodeType进行判断

2024-08-11 22:13 UTC, chivehao commented on data-sources/ikaros/src/IkarosClient.kt
> +        var ikarosEpisodeGroup = "MAIN";
没明白，你是指find需要改？

2024-08-12 02:37 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +        episodeSort = Special(prefix + int.toString())
可以把EpisodeType挪进来

2024-08-12 02:39 UTC, chivehao commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +        episodeSort = Special(prefix + int.toString())
不用，我直接新建了个enum

2024-08-12 03:36 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +        episodeSort = Special(prefix + int.toString())
no, 我们不要维护两个 enum, 移过来是最好的选择

2024-08-12 03:42 UTC, chivehao commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +        episodeSort = Special(prefix + int.toString())
不用维护额，bangumi的api的episode type就那几个，而且估计后续不会变动。
额，实话是我嫌弃要分析整个项目的依赖结构很麻烦，之前初步尝试过，没看出来最底层的依赖是哪个，我不清楚要移动到哪。

2024-08-12 03:54 UTC, Him188 commented on data-sources/ikaros/src/IkarosClient.kt
> +        var ikarosEpisodeGroup = "MAIN";
他说的应该是 

```kotlin
val ikarosEpisodeGroup = when(   ) {

```

避免使用 var. 这是比较 idomatic kotlin 的

2024-08-12 16:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/models/subject/SubjectManager.kt
> +    abstract val showAllEpisodes: Flow<Boolean>
不需要公开吧

2024-08-12 16:20 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +fun EpisodeSort(int: BigNum, type: Int): EpisodeSort {
不要用 int, 用 `EpisodeType`

2024-08-12 16:20 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +fun EpisodeSort(int: BigNum, type: Int): EpisodeSort {
其他重载也应当支持这个

2024-08-12 16:20 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeType.kt
> +        fun codeOf(code: Int): EpisodeType {
```suggestion
        fun fromCodeOrOther(code: Int): EpisodeType {

```

2024-08-12 16:20 UTC, Him188 commented on data-sources/ikaros/src/IkarosClient.kt
> +                EpisodeType.OTHER.name -> IkarosEpisodeGroup.OTHER
依赖这个 name 是不稳定的, 以后可能会改, 而且有可能会在安卓 release 时因为混淆而丢失

2024-08-12 16:20 UTC, Him188 commented on data-sources/ikaros/src/IkarosClient.kt
> +            val typeStr = episodeSort.toString().subSequence(0, endIndex)
```suggestion
            val typeStr = episodeSort.toString().substringBefore(endIndex)
```

2024-08-12 16:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/models/subject/SubjectManager.kt
> +    abstract val showAllEpisodes: Flow<Boolean>
因为没别的地方用到

2024-08-12 18:05 UTC, chivehao commented on app/shared/src/commonMain/kotlin/data/models/subject/SubjectManager.kt
> +    abstract val showAllEpisodes: Flow<Boolean>
会加个protected修饰符

2024-08-12 18:26 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +fun EpisodeSort(int: BigNum, type: Int): EpisodeSort {
是的

2024-08-13 05:52 UTC, Him188 requested changes

2024-08-13 05:52 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/models/subject/SubjectManager.kt
> +    protected abstract val showAllEpisodes: Flow<Boolean>
我觉得可以从 abstract  class 里面删掉这个

2024-08-13 05:52 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/repository/BangumiEpisodeRepository.kt
> +        sort = EpisodeSort(this.sort, EpisodeType.fromCodeOrOther(this.type)),
如果是 bangumi code 转换到 ani EpisodeSort 的话, 那实际上应该在 bangumi 这里写一个 
`fun getEpisodeSortByCode(code: Int): EpisodeSort`

因为 EpisodeSort 设计上应当是与数据源无关

2024-08-13 05:52 UTC, Him188 commented on data-sources/ikaros/src/IkarosClient.kt
> +                episodeSort.number.toString()
这可能为 `"null"`

2024-08-13 05:52 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +fun EpisodeSort(int: BigNum, type: EpisodeType): EpisodeSort {
建议删除原来的 `fun EpisodeSort(int: BigNum): EpisodeSort {`, 改成用默认参数:
```suggestion
fun EpisodeSort(int: BigNum, type: EpisodeType = EpisodeType.MainStory): EpisodeSort {
```

让重载数量尽快少一点

2024-08-13 05:52 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +fun EpisodeSort(int: BigNum, type: EpisodeType): EpisodeSort {
上面的 int/string 重载 `fun EpisodeSort(raw: String): EpisodeSort {` 也应当支持 type:
```kotlin
fun EpisodeSort(raw: String, type: EpisodeType = EpisodeType.MainStory): EpisodeSort {
```

2024-08-13 21:29 UTC, chivehao commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +fun EpisodeSort(int: BigNum, type: EpisodeType): EpisodeSort {
raw本就是直接赋予这个参数值，也需要支持type嘛，我有点无处下手，不知道咋修改合适
![image](https://github.com/user-attachments/assets/3f788c6b-79f0-40ee-b9db-5addca2f4756)

2024-08-14 02:11 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +fun EpisodeSort(int: BigNum, type: EpisodeType): EpisodeSort {
o，那就不用加

2024-08-14 04:37 UTC, chivehao commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +fun EpisodeSort(int: BigNum, type: EpisodeType): EpisodeSort {
好的，已经push的commit这个方法没改，也就是没有像上面截图里加上选中的type参数。

2024-08-14 05:41 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeType.kt
> +        fun fromCodeOrOther(code: Int): EpisodeType {
remove

2024-08-14 05:41 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeType.kt
> +enum class EpisodeType(val code: Int, val value: String) {
remove code

2024-08-14 05:41 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/repository/BangumiEpisodeRepository.kt
> +        type = EpisodeType.fromCodeOrOther(this.type),
```suggestion
        type = getEpisodeTypeByBangumiCode(this.type),
```

2024-08-14 05:41 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/repository/BangumiEpisodeRepository.kt
> +fun getEpisodeSortByBangumiEpisodeCode(bangumiEpisodeTypeCode: Int): EpisodeType {
```suggestion
private fun getEpisodeTypeByBangumiCode(code: Int): EpisodeType {
```

2024-08-14 05:41 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/repository/BangumiEpisodeRepository.kt
> +    return EpisodeType.fromCodeOrOther(bangumiEpisodeTypeCode)
把那个 when 挪过来

2024-08-14 08:08 UTC, chivehao commented on data-sources/api/src/commonMain/kotlin/EpisodeType.kt
> +enum class EpisodeType(val code: Int, val value: String) {
意思是直接用索引？

2024-08-14 08:08 UTC, chivehao commented on data-sources/api/src/commonMain/kotlin/EpisodeType.kt
> +enum class EpisodeType(val code: Int, val value: String) {
我感觉用索引这种方式不好，更容易导致出错。

2024-08-14 08:48 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/models/episode/EpisodeInfo.kt
>          "PV$sort"
这些 render 结果不对吧, 我感觉它会是 `OPOP01`, 增加点 test 看看?

2024-08-14 09:00 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
>      ) : EpisodeSort() {
总感觉这里有点怪怪的, 我觉得应当让 Special 表示能正确解析的 SP/OP/ED 类型, 然后另外加一个 Unknown, 直接传入 raw.
这样数据源无需自己去解析 `Special.raw` 来判断是 OP 还是 ED. 

```kotlin
@Serializable
class Special internal constructor(
    val type: EpisodeType,
    override val number: Float?,
) {
    val raw: String get() = "${type.value}$number" // "SP01"
// ...
}

@Serializable
class Unknown internal constructor(
    override val raw: String
)
```

`EpisodeSort` 会参与序列化, 会成为缓存元数据, 也就是一旦发布后就无法修改, 需要谨慎

2024-08-14 09:02 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
>      ) : EpisodeSort() {
目前不会有 Special 类型已经序列化到硬盘了, 所以可以更改结构

2024-08-16 15:54 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +        return Special(MAD, numStr.toFloat())
带有 0 应该也能 toFloat 吧

2024-08-16 15:54 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +            Special(type, numStr.toFloat())
带有 0 应该也能 toFloat 吧

2024-08-16 15:54 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +            val typeStr = raw.subSequence(0, 2).toString()
这不对吧, OVA 怎么办
应该 filter 非数字

2024-08-16 15:54 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
>  fun EpisodeSort(int: Int): EpisodeSort {
```suggestion
fun EpisodeSort(int: Int, type: EpisodeType = MainStory): EpisodeSort {
```

2024-08-16 15:54 UTC, Him188 commented on data-sources/api/src/commonTest/kotlin/EpisodeSortTest.kt
>              ).map {
加一下 OVA, OAD

2024-08-16 15:54 UTC, Him188 commented on data-sources/api/src/jvmMain/kotlin/Episode.jvm.kt
>  fun EpisodeSort(int: BigDecimal): EpisodeSort {
要加个 type 参数

2024-08-16 15:54 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeType.kt
> +    OTHER("OTHER");
我觉得应该去掉 Other, 属于 Other 的当 Unknown

2024-08-17 08:42 UTC, Him188 reviewed
我的意思其实是从 Special 里去掉 Unknown 类型, 而使用 `EpisodeSort.Unknown`

2024-08-17 13:09 UTC, chivehao commented on app/shared/src/commonMain/kotlin/data/repository/BangumiEpisodeRepository.kt
> +        else -> SP
这里的6，对应Bangumi的EpisodeType.Other，因为EpisodeType没有了Unknow和Other类型，我这边去掉了6和把其它情况都配置成了SP

2024-08-17 13:14 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/repository/BangumiEpisodeRepository.kt
> +        else -> SP
应该是要是 Unknown 吧

2024-08-17 13:15 UTC, chivehao commented on app/shared/src/commonMain/kotlin/data/repository/BangumiEpisodeRepository.kt
> +        else -> SP
这个方法返回的是EpisodeType，Unknown已经去掉了

2024-08-17 13:16 UTC, chivehao commented on app/shared/src/commonMain/kotlin/data/repository/BangumiEpisodeRepository.kt
> +        else -> SP
或者返回null，然后再在调用方配置EpisodeSort.Unkonw也行

2024-08-17 13:25 UTC, chivehao commented on app/shared/src/commonMain/kotlin/data/repository/BangumiEpisodeRepository.kt
> +        else -> SP
> 或者返回null，然后再在调用方配置EpisodeSort.Unkonw也行

这样也不好整

2024-08-17 14:48 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/repository/BangumiEpisodeRepository.kt
> +        else -> SP
那就返回 null

2024-08-17 15:11 UTC, chivehao commented on app/shared/src/commonMain/kotlin/data/repository/BangumiEpisodeRepository.kt
> +        else -> SP
> 那就返回 null
那个EpisodeInfo里的type也可以为null嘛？

2024-08-17 15:46 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/repository/BangumiEpisodeRepository.kt
> +        else -> SP
可以, null 表示不知道, 挺好的

2024-08-18 10:20 UTC, Him188 reviewed
基本上 OK 了, 辛苦再处理一下边界问题和增加一些 test (见评论)

----

可能还要考虑比较顺序, 有以下几个关键问题要测试到, 因为它们会影响 UI 里面的排序:
1. 所有特殊类型都要大于正片: `1 < 1.5 < 2 < OP < ED`
2. 加一个测试 case, 展示目前所有类型特殊剧集的排序情况 (先无需考虑是否正确, 只需要展示一下看看)

以下开放问题可以不用在这个 PR 解决:

3. 特殊剧集排序问题,  `OP < ED` 应该没什么异议, 但是 SP 和 OVA 应该怎么排序? 肯定放在正片后面, 跟 OP ED 到一起了又该怎么排序?

2024-08-18 10:20 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +    if (type == null || raw.length < type.value.length) return EpisodeSort.Unknown(raw)
```suggestion
    val type = EpisodeType.entries.firstOrNull { entry -> raw.startsWith(entry.value, ignoreCase = true) }
        ?: return EpisodeSort.Unknown(raw)
```

`raw.length < type.value.length` 永远为 `false`

2024-08-18 10:20 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +    return Special(type, numStr.toFloatOrNull())
```suggestion
    return Special(type, numStr.toFloatOrNull())
```

这个逻辑可能是有问题的:
- `SP-1` 期望是 `Unknown("SP-1")` 而不是 `Special(SP, null)`. 目前 `EpisodeSort(-1)` 也是会返回 Unknown 的, 行为需要保持一致. 允许负数也会导致 compare 出问题, 目前应该是拿字符串比较的
- `SPAB` 期望是 `Unknown("SPAB")` 而不是 `Special(SP, null)`

2024-08-18 10:20 UTC, Him188 commented on data-sources/api/src/commonTest/kotlin/EpisodeSortTest.kt
> +                "S" to EpisodeSort.Unknown("S"),
辛苦补充一下 `SPSP`, `SP-1`, `SP1.1`, `SP0` 的 case (期望都是 Unknown)

2024-08-18 10:20 UTC, Him188 commented on data-sources/api/src/commonTest/kotlin/title/generated/PatternTitleParserTest间谍过家家.kt
> +    assertEquals("SP..SP", r.episodeRange.toString())
这个变更是不符合预期的, 虽然原本识别出 `SPY×FAMILY..SPY×FAMILY` 也是 bug

2024-08-18 10:25 UTC, Him188 requested changes

2024-08-18 10:25 UTC, Him188 commented on data-sources/api/src/commonMain/kotlin/EpisodeSort.kt
> +}
这个实现会导致可以绕过必须为 .5 的倍数的限制:

`EpisodeSort("SP1.1")` 是 Unknown, 但是 `EpisodeSort(BigNum("1.1"), SP)` 会是 `Special(SP, 1.1)` 

辛苦增加一些调用 `fun EpisodeSort(int: BigNum, type: EpisodeType? = MainStory)` 这个重载的 test case

2024-08-18 11:20 UTC, chivehao commented on data-sources/api/src/commonTest/kotlin/title/generated/PatternTitleParserTest间谍过家家.kt
> +    assertEquals("SP..SP", r.episodeRange.toString())
这个咋整？

2024-08-18 13:49 UTC, chivehao commented on data-sources/api/src/commonTest/kotlin/title/generated/PatternTitleParserTest间谍过家家.kt
> +    assertEquals("SP..SP", r.episodeRange.toString())
应该都改回去了

2024-08-18 14:19 UTC, Him188 approved these changes

2024-08-18 15:52 UTC, Him188 commented
Test 在 ios 上失败了

https://scans.gradle.com/s/wmja75jrq3ime/tests/task/:data-sources:api:iosSimulatorArm64Test/details/me.him188.ani.datasources.api.EpisodeSortTest/testCompareTo?top-execution=1

但在其他平台成功了, 很有意思

2024-08-18 18:08 UTC, Him188 commented on data-sources/api/src/commonTest/kotlin/EpisodeSortTest.kt
> +            Pair(ep("1.1"), ep("SP3.2")) to "1.1".compareTo("SP3.2"), // raw compare to
`"1.1".compareTo("SP3.2")`
可以返回任意值, `compareTo` 只定义了负数代表小于, 没要求必须是 `-1`

2024-08-19 01:10 UTC, chivehao commented on data-sources/api/src/commonTest/kotlin/EpisodeSortTest.kt
> +            Pair(ep("1.1"), ep("SP3.2")) to "1.1".compareTo("SP3.2"), // raw compare to
是这样，这块是小数，所以测试案例里预期不是-1，而是 执行 raw.compareTo(other.raw)这个逻辑，
实际则根据字符串的比较进行。

2024-08-19 19:33 UTC, Him188 approved these changes

2024-08-19 19:34 UTC, merged