修复了老版本弹幕正则过滤的问题
open-ani/ani pull request #797
Opened 2024-08-21 23:23 UTC by rdlwicked

1. 在播放器中添加了弹幕过滤侧边栏，解决了系统状态栏弹出的问题，提高了可读性
2. 创建了一个state管理弹幕过滤的相关状态
3. 在主设置添加了之前的弹幕过滤管理组

2024-08-22 17:53 UTC, Him188 requested changes
1. 格式化所有相关文件然后勾选 
![image](https://github.com/user-attachments/assets/6983634e-7590-4735-810b-cc092494db72)

2. 添加一些截图
    - 没有任何 filter 时的列表界面
    - 有两个 filter 时的列表界面
    - 有两排 filter 的列表界面
    - 编辑界面

3. 手机竖屏有没有禁止编辑?

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/androidMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.android.kt
> +fun PreviewAddDanmakuRegexFilterSideSheet() {
```suggestion
fun PreviewEditDanmakuRegexFilterSideSheet() {
```

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +    val showCursor by remember(videoControllerState, showSettings) {
```suggestion
    val showCursor by remember(videoControllerState) {
```

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                if (showSettings) {
Use else if to remove one indent level

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                        showSettings = true
如果是关闭过滤设置, 我觉得应该要回到一级菜单
```suggestion
```

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +    onRemoveDanmakuRegexFilter: (DanmakuRegexFilter) -> Unit,
extract state

否则太多参数了

```kotlin
class DanmakuRegexFilterManagerState(
    danmakuRegexFilterList: State<List<DRF>>,
    val add: (DanmakuRegexFilter) -> Unit,
    val switch: (DanmakuRegexFilter) -> Unit,
    ...
) {
    val danmakuRegexFilterList by danmakuRegexFilterList
}
```

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                showSettings = false
不能在 composition 中修改 state

考虑用单个 enum 变量来替代这两个 show

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +    fun switchDanmakuRegexFilter(filter: DanmakuRegexFilter)
extract state

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/EpisodeVideoSettings.kt
> +    onOverlayContentShow: () -> Unit,
```suggestion
    onClickManage: () -> Unit,
```

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/EpisodeVideoSettings.kt
> +                onClick = {onOverlayContentShow()},
reformat this file

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/EpisodeVideoSettings.kt
> +                modifier = Modifier.placeholder(isLoadingState).clickable{onOverlayContentShow()}.padding(bottom = 8.dp,top = 8.dp)
```suggestion
                modifier = Modifier.placeholder(isLoadingState).padding(bottom = 8.dp,top = 8.dp)
```
redundant

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/EpisodeVideoSettings.kt
> +        onOverlayContentShow = { onOverlayContentShow() },
```suggestion
        onOverlayContentShow = onOverlayContentShow,
```

waste of memory

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                regexTextFieldOutlineTitleText = "正则输入法不能为空"
```suggestion
                regexTextFieldOutlineTitleText = "请输入正则表达式"
```

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                regexTextFieldOutlineTitleText = "正则输入法不能为空"
这个 text 不是用来展示 error 的, 
OutlinedTextField  有个 `error = ` 可以展示

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                        )
需要支持在 PC 上使用回车键完成添加

`Modifier.onKeyEvent`

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                            onClick = { handleAdd() },
```suggestion
                            onClick = handleAdd,
```

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                            Text(color = MaterialTheme.colorScheme.primary, text = "添加")
```suggestion
                            Text("添加")
```

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                    Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {
加起来有 32 horizontal padding, 我猜太多了

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                        danmakuRegexFilterList.forEachIndexed { index, item ->
unused index, use forEach instead

2024-08-22 17:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                        horizontalArrangement = Arrangement.spacedBy(8.dp),
missing vertical arrangement?

2024-08-22 17:53 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuFilterConfig.kt
> +    val danmakuRegexFilterEnabled: Boolean = true,
```suggestion
    val enableRegexFilter: Boolean = true,
```

2024-08-24 20:07 UTC, rdlwicked commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                    Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {
这是因为outlined text filed title比较长输入时会显示到上方，padding太小会导致文字被遮挡
<img width="288" alt="Screenshot 2024-08-24 at 21 07 29" src="https://github.com/user-attachments/assets/72e3e7be-be15-42ca-b9ca-020722a48c02">

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/subject/episode/EpisodeVideoControllerTest.kt
> +                ),
写一个共享的函数 `createTestDanmakuRegexFilterState()` 将 `addDanmakuRegexFilter` 提供默认值, 来避免重复这些代码, 也能减轻以后如果要修改 `DanmakuRegexFilterState` 的时候, 需要同时修改的地方.

example:

https://github.com/open-ani/ani/blob/e5b1741f9c44bbbd34076b0bbbda77a71fef39e9/app/shared/src/androidMain/kotlin/ui/cache/CacheManagePage.android.kt#L54-L93

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                                    text = regexTextFieldOutlineTitleText,
```suggestion
                                    text =  if (expanded) {
            "填写用于屏蔽的正则表达式，例如：‘.*签.*’ 会屏蔽所有含有文字‘签’的弹幕。"
        } else {
            "竖屏状态下无法编辑"
        }
```

直接写到这里面更好

记得 format 一下

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +        modifier = modifier.testTag(TAG_EPISODE_SELECTOR_SHEET)
```suggestion
        modifier = modifier
```

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +    var isError by rememberSaveable { mutableStateOf(false) }
```suggestion
    val isError by remember { derivedStateOf { regexTextFieldValue.isBlank() } }
```

一般来说不要使用 `var` 这种 "回调" 的更新模式, 用 val derivedState 是让逻辑明显更清晰的

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/EpisodeVideoSettings.kt
> +    switchDanmakuRegexFilterCompletely: () -> Unit,
这些参数要放在 modifier 前面

modifier 的后面只能放可选参数或一个 `@Composable` labda

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/EpisodeVideoSettings.kt
> +                title = { Text("正则弹幕过滤器开启") },
```suggestion
                title = { Text("启用正则弹幕过滤器") },
```

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/EpisodeVideoSettings.kt
> +    onOverlayContentShow: () -> Unit = { }
该参数要在 modifier 上面, 而且不应当有默认值

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/EpisodeVideoSettings.kt
> +    onClickManage: () -> Unit,
```suggestion
    onManageRegexFilters: () -> Unit,
```

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/EpisodeVideoSettings.kt
> +    enableRegexFilter: Boolean,
这个放到 `onClickManage` 上面, 一般的偏好是相关的属性在 callback 上面

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/EpisodeVideoSettings.kt
> +    onOverlayContentShow: () -> Unit = { }
```suggestion
    onManageRegexFilters: () -> Unit = { }
```

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/DanmakuRegexFilterState.kt
> +) {
```suggestion
@Stable
class DanmakuRegexFilterState(
    list: State<List<DanmakuRegexFilter>>,
    val add: (filter: DanmakuRegexFilter) -> Unit,
    val edit: (id: String, new: DanmakuRegexFilter) -> Unit,
    val remove: (filter: DanmakuRegexFilter) -> Unit,
    val toggleEnabled: (filter: DanmakuRegexFilter) -> Unit,
) {
```

简短

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/DanmakuRegexFilterState.kt
> +    val danmakuRegexFilterList by danmakuRegexFilterList
```suggestion
    val list by list
```

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/DanmakuRegexFilterGroup.kt
> +                        label = { Text("填写用于屏蔽的正则表达式，例如：‘.*签.*’ 会屏蔽所有含有文字‘签’的弹幕。") },
```suggestion
                        label = { Text("填写用于屏蔽的正则表达式，例如：‘.*签.*’ 会屏蔽所有含有文字‘签’的弹幕") },
```

短句没有句号

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/DanmakuRegexFilterGroup.kt
> +        title = { Text("正则弹幕过滤器管理", color = MaterialTheme.colorScheme.onSurface) },
```suggestion
        title = { Text("弹幕正则过滤器管理", color = MaterialTheme.colorScheme.onSurface) },
```

这样会好点吧

因为之后可能要加 "弹幕云过滤设置" 之类的

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/DanmakuRegexFilterGroup.kt
> +    var isError by rememberSaveable { mutableStateOf(false) }
```suggestion
    val isError by remember { derivedStateOf { regex.isBlank() } }
```

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/DanmakuRegexFilterGroup.kt
> +    danmakuRegexFilterState: DanmakuRegexFilterState,
```suggestion
    state: DanmakuRegexFilterState,
```

对于 composable 的唯一一个 state 参数, 一般就叫做 `state` 以保证代码简短

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +    )
```suggestion
    fun editDanmakuRegexFilter(id: String, new: DanmakuRegexFilter) {
        launchInBackground { danmakuRegexFilterRepository.update(id, new) }
    }

    fun removeDanmakuRegexFilter(filter: DanmakuRegexFilter) {
        launchInBackground {
            danmakuRegexFilterRepository.remove(filter)
        }
    }

    fun switchDanmakuRegexFilter(filter: DanmakuRegexFilter) {
        launchInBackground {
            danmakuRegexFilterRepository.update(filter.id, filter.copy(enabled = !filter.enabled))
        }
    }
    
    override val danmakuRegexFilterState = DanmakuRegexFilterState(
        danmakuRegexFilterList = danmakuRegexFilterRepository.flow.produceState(emptyList()),
        addDanmakuRegexFilter = { launchInBackground { danmakuRegexFilterRepository.add(it) } },
        editDanmakuRegexFilter = ::editDanmakuRegexFilter,
        removeDanmakuRegexFilter = ::removeDanmakuRegexFilter,
        switchDanmakuRegexFilter = ::switchDanmakuRegexFilter,
    )
```

其他几个也改一下. 

这种情况一般就地写 lambda, 更简短, 只有 lambda 的内容很大的时候才会抽一个函数

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +enum class SideSheetState {
```suggestion
private enum class SideSheetState {
```

`SideSheetState` 名字很通用, 如非必要不要 public. public 会污染全局命名空间

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/app/AppSettingsTab.kt
> +            title = { Text("正则弹幕过滤器开启") },
```suggestion
            title = { Text("启用正则弹幕过滤器") },
```

2024-08-25 11:20 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/app/AppSettingsTab.kt
> +        addDanmakuRegexFilter = ::addDanmakuRegexFilter,
这些也可以就地写 lambda

2024-08-25 15:34 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +            Surface {
```suggestion
            Surface(Modifier
                .fillMaxWidth()
                .clickable { focusManager.clearFocus() }) {
```
多余 box

2024-08-25 15:34 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                    Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) {
这么长的东西应该用 supportingText 而不是 label

2024-08-25 15:35 UTC, Him188 commented
如果回复了我的 review, 不要点 resolve conversation, 否则我会看不到回复

2024-08-27 21:16 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                                text = "填写用于屏蔽的正则表达式，例如：‘.*签.*’ 会屏蔽所有含有文字‘签’的弹幕。",
正则不应该是完全匹配, 应当是包含就算. 也就是如果用户填写 "签" 就足以屏蔽所有含有文字‘签’的弹幕.
需要把过滤那边也改一下

2024-08-27 21:16 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/DanmakuRegexFilterGroup.kt
>  ) {
为什么还需要有这个 dialog? 不是换成 side sheet 了吗

2024-08-27 21:19 UTC, Him188 requested changes

2024-08-27 21:19 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                ) {
![image](https://github.com/user-attachments/assets/2d19e5e5-a3cc-438a-96ad-fc434b41cb73)

建议改成这样 row, 左边是编辑框, 右边是 IconButton

2024-08-27 21:19 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/sidesheet/EditDanmakuRegexFilterSideSheet.kt
> +                    verticalArrangement = Arrangement.spacedBy(8.dp),
```suggestion
```
不需要有吧, 看你图上这个已经挺大了

2024-08-28 23:54 UTC, rdlwicked commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/DanmakuRegexFilterGroup.kt
>  ) {
在主设置菜单中调整会使用dialog

2024-08-28 23:55 UTC, rdlwicked commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/DanmakuRegexFilterGroup.kt
>  ) {
在主菜单中没有系统状态栏的问题

2024-08-29 00:02 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/settings/DanmakuRegexFilterGroup.kt
>  ) {
ok，听起来没问题

2024-09-11 17:12 UTC, Him188 approved these changes
Need QA

2024-09-11 17:14 UTC, merged