Rewrite danmaku renderer
open-ani/ani pull request #836
Opened 2024-08-27 11:12 UTC by StageGuard

重新写了弹幕引擎

## 主要修改

不再使用 `trackOffset`，因为原先的实现为每一个 floating track 都启动 `animateMove`，这可能会影响性能。

现在改用 `timeOffset`，`DanmakuHostState` 接收 playTimeMillis flow，作为 timeOffset state。
playTimeMillis flow 在不同平台有不同实现，接收 playTimeMillis 的速度可能比较慢（例如现在 desktop 和 android 都是 10 fps），所以在 `DanmakuHostState` 中实现了 `interpolateFrame`（类似之前的 `animateMove`）来在接收 playTimeMillis 的间隔插值计算 `timeOffset`，让弹幕能够平滑滚动。

## 次要修改

* `DanmakuConfig` 现在放到了 `DanmakuHostState` 中，不再随着 composable 提供。
* 修复了 `List<DanmakuSession>.merge()` 中 repopulate 的 bug。`requestRepopulate` 后应该收到所有的 repopulate event 后合并发送到下游 event flow。

2024-08-27 12:16 UTC, Him188 commented on danmaku/ui/commonMain/new/DanmakuState.kt
> +data class DanmakuState(
如果使用 derivedStateOf, 那就应当是 `@Stable`

2024-08-27 12:16 UTC, Him188 commented on danmaku/ui/commonMain/new/DanmakuState.kt
> +    val solidTextLayout by lazy {
do you need lazy?

2024-08-27 12:16 UTC, Him188 commented on danmaku/ui/commonMain/new/DanmakuHostState.kt
> +    internal suspend fun interpolateFrame() {
```suggestion
    internal suspend fun interpolateFrameLoop() {
```

突出它是不会正常 return 的

2024-08-27 12:16 UTC, Him188 commented on danmaku/ui/commonMain/new/DanmakuHostState.kt
> +                    var glitched = false
explain this

2024-08-27 12:16 UTC, Him188 commented on danmaku/ui/commonMain/new/DanmakuHostState.kt
> +            launch {
应该用 collectLatest 吧

`progress.collectLatest { `

2024-08-27 12:16 UTC, Him188 commented on danmaku/ui/commonMain/new/DanmakuHostState.kt
> +                withContext(Dispatchers.Main.immediate) {
是没有必要的, 因为上面用了 snapshotFlow, 这个就必须在 main collect, 所以 measureTrack 一定已经在 main 调用了

2024-08-27 12:16 UTC, Him188 commented on danmaku/ui/commonMain/new/DanmakuHost.kt
> +        Canvas(Modifier.size(width, height)) {
本质上就是
```suggestion
        Canvas(Modifier.fillMaxSize()) {
```
可以减少一帧延迟

2024-08-27 12:20 UTC, StageGuard commented on danmaku/ui/commonMain/new/DanmakuHost.kt
> +    LaunchedEffect(trackStubMeasurer) { state.measureTrack(trackStubMeasurer, density) }
需要 collect flow，可以省略吗？

2024-08-27 12:22 UTC, StageGuard commented on danmaku/ui/commonMain/new/DanmakuHost.kt
> +        Canvas(Modifier.size(width, height)) {
这是为了防止不知道什么情况的情况导致 canvas size 与 host state 中保存的不一样

2024-08-27 13:49 UTC, Him188 commented on danmaku/ui/commonMain/new/DanmakuHost.kt
> +    LaunchedEffect(trackStubMeasurer) { state.measureTrack(trackStubMeasurer, density) }
那就不可以，这个命名让我不认为它是会跑很久的

2024-08-27 14:21 UTC, Him188 commented on danmaku/ui/commonMain/new/DanmakuHost.kt
> +        Canvas(Modifier.size(width, height)) {
fillMaxSize然后onSizeChanged

2024-08-27 16:03 UTC, StageGuard commented on danmaku/ui/commonMain/new/DanmakuHost.kt
> +    LaunchedEffect(trackStubMeasurer) { state.measureTrack(trackStubMeasurer, density) }
那我可以改一个名字

2024-08-27 18:04 UTC, Him188 requested changes
把旧的全删了然后有 profile 数据之后再 request 我

2024-08-27 18:04 UTC, Him188 commented on danmaku/api/src/commonMain/kotlin/DanmakuSession.kt
> +            var repopulateDeferred: List<CompletableDeferred<DanmakuEvent.Repopulate>>? = null
不对吧, 这个实现太 complex 了, 就不应该有 `List<DanmakuSession>`, 应当只有一个. 应该查询完所有源的弹幕之后, 把它们都放到同一个 `TimeBasedDanmakuSession` 里

2024-08-27 18:04 UTC, Him188 commented on danmaku/ui/androidMain/NewDanmakuHost.android.kt
> +class NewDanmakuHost {
remove

2024-08-28 08:00 UTC, Him188 commented
hi, resolve conversations please

2024-08-30 07:58 UTC, Him188 reviewed
需要增加测试, 包括但不限于

- UI test case https://github.com/open-ani/ani/issues/511

2024-08-30 07:58 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/VideoDanmakuState.kt
> +                    danmakuHostState.trySend(DanmakuPresentation(danmaku, isSelf = true))
对于用户自己发的弹幕, 一定要发出去

2024-08-30 07:58 UTC, Him188 commented on danmaku/api/src/commonMain/kotlin/DanmakuSession.kt
> +            var repopulateDeferred: List<CompletableDeferred<DanmakuEvent.Repopulate>>? = null
可以给这个开个 issue

2024-08-30 07:58 UTC, Him188 commented on danmaku/ui/androidMain/DanmakuHost.android.kt
> +    override fun switchDanmakuRegexFilter(filter: DanmakuRegexFilter) { }
do not change this


you will cause conflict with another PR

2024-08-30 07:58 UTC, Him188 commented on danmaku/ui/androidMain/DanmakuHost.android.kt
> +package me.him188.ani.danmaku.ui.new
fix

2024-08-30 07:58 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHost.kt
> -
should keep this

2024-08-30 07:58 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuState.kt
> +    val isDebug: Boolean
```suggestion
   isDebug: Boolean
```

2024-08-30 07:58 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuTrack.kt
> +    val frameTimeNanos: LongState
usually

```suggestion
interface DanmakuTrack {
    val frameTimeNanos: Long
```

2024-08-30 07:58 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuTrack.kt
> +    val onRemoveDanmaku: (DanmakuHostState.PositionedDanmakuState) -> Unit
does not make sense to be val

2024-08-30 07:58 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuTrackProperties.kt
> +@Stable
```suggestion
@Immutable
```

2024-08-30 07:58 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuTrackProperties.kt
> +        val Default = DanmakuTrackProperties()
```suggestion
        @Stable
        val Default = DanmakuTrackProperties()
```

2024-08-30 07:58 UTC, Him188 commented on danmaku/ui/commonMain/FastSumQueue.kt
> +    private val queue: Array<Long> = Array(queueSize) { 0L }
```suggestion
    private val queue: LongArray = LongArray(queueSize)
```

2024-08-30 07:58 UTC, Him188 commented on danmaku/ui/commonMain/FixedDanmakuTrack.kt
> +    private val durationMillis: State<Long> = mutableStateOf(5000L),
```suggestion
    private val durationMillis: LongState = mutableStateOf(5000L),
```

2024-08-30 08:44 UTC, Him188 requested changes

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/FixedDanmakuTrack.kt
> + * - [FixedDanmakuTrack.place] 覆盖了正在显示的弹幕
should be tested

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/FixedDanmakuTrack.kt
> + * - tick 中的逻辑帧检测
should be tested

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/FixedDanmakuTrack.kt
> + * - 调用 [DanmakuTrack.clearAll]
should be tested

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/FixedDanmakuTrack.kt
> +    private val screenHeight: IntState,
should test `place` & `tryPlace` if `screenWidth` and/or `screenHeight` and/or `trackHeight` are 0

(state test, not ui test)

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/FixedDanmakuTrack.kt
> +    internal var currentDanmaku: FixedDanmaku? = null
no need to be public

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    private val danmakuTrackProperties: DanmakuTrackProperties = DanmakuTrackProperties.Default, // state
state?

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +        }
这是不期望的吧, 不期望就 `throw ISE`

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +        }
这个写法可能会导致没法跑 ui case, 因为 ui test 时 delay 会被忽略
可能需要某种同步机制例如 CompletableDeferred 来 suspend, 不要对外暴露属性, 封装一个函数来设置这两个属性并且 complete

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +        ) { config, height ->
我觉得需要 UI 去 debounce height, 然后调用这个函数来计算, 否则比较难 unit test

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    val presentDanmaku: List<PositionedDanmakuState> = mutablePresentDanmaku
do you need it public?

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    internal val bottomTrack: MutableList<FixedDanmakuTrack> = mutableListOf()
make them as private as possible

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    internal lateinit var density: Density
```kotlin
class UIContext(val baseStyle, val textMeasurer)
private lateinit var uiContext: 
```

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    internal suspend fun observeTrack(measurer: TextMeasurer, density: Density) {
class 里有 textMeasurer 和 density, 这里为什么又有

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    internal var trackHeight by trackHeightState
why internal

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +                    elapsedFrameTimeNanos += avgFrameTimeNanos.avg()
no need

补多了导致弹幕会跳回去. 而且这个就一帧, 只会在暂停之后恢复时跳过一帧, 问题不大

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +            launch {
no need

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    }
move to file level

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +                    }
目前我没有看到足够的理由来维护 `elapsedFrameTimeNanos` 和 avgFrameTimeNanos

use `nanos` strictly:

```suggestion
                    withFrameNanos { nanos ->
                        currentFrameTimeNanos = nanos
                    }
```

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +            launch {
no need

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +                while (isActive) {
```suggestion
                while (true) {
```

`delay` always check for cancellation

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +                    delay(1000 / 30) // 30 fps
10 is enough?
```suggestion
                    delay(1000 / 10)
```

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuState.kt
> +    val enableColor: Boolean,
`enableColor` 不应该是 danmaku 级别吧

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +        }
违反了 equals 的约定

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    ) : PositionedDanmakuState by correspondingState {
does not sound correct to me \

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    fun setPause(pause: Boolean) {
```suggestion
    fun setPaused(paused: Boolean) {
```

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +            val mapped = mutablePresentDanmaku.map { OverridePlaceTimeDanmakuState(it, it.placeFrameTimeNanos) }
重新创建, 而不要 hack

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    suspend fun repopulate(list: List<DanmakuPresentation>) {
repopulate, repopulatePositioned, invalidate, 太多了

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +            }
complex logic

跟以前一样, 先获取对应的 track, 再 tryPlace, 这才是为什么需要有那个接口 DanmakuTrack

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    private val mutablePresentDanmaku: MutableList<PositionedDanmakuState> = mutableStateListOf()
难道不应该是每个 track 存这个吗

你可以为了 locality, 把所有浮动的存到一起, 但并不 make sense 把 fixed 也存一起

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    private val mutablePresentDanmaku: MutableList<PositionedDanmakuState> = mutableStateListOf()
不需要 stateList 吧

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    ): PositionedDanmakuState? {
```suggestion
    // 向指定帧时间的位置发送弹幕
    private suspend fun trySend(
        danmaku: DanmakuPresentation, 
        placeFrameTimeNanos: Long = elapsedFrameTimeNanos
    ): PositionedDanmakuState? = withContext(Dispatchers.Main.immediate) {
```

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/FloatingDanmakuTrack.kt
> +            val timeDiff = (frameTimeNanos.value - placeFrameTimeNanos) / 1_000_000_000f
弹幕的首帧时间应该是一个内在属性, 需要使用 UI 运动时的第一帧, `placeFrameTimeNanos` 不行

假设第 1000ms 时放置弹幕, 1025ms 才下一个 ui 帧, 那你的弹幕就瞬移了 25ms

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/FloatingDanmakuTrack.kt
> +    // 检测是否有弹幕的右边缘坐标大于此弹幕的左边缘坐标
写  `/**` 注释

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/FloatingDanmakuTrack.kt
> +    override val frameTimeNanos: LongState,
DanmakuTrack 接口不应该有 frameTime

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/FloatingDanmakuTrack.kt
> +    private val screenWidth: IntState,
```suggestion
    private val trackWidth: IntState,
```

2024-08-30 08:44 UTC, Him188 commented on danmaku/ui/commonMain/FloatingDanmakuTrack.kt
> +    override val onRemoveDanmaku: (DanmakuHostState.PositionedDanmakuState) -> Unit
看起来不应该有这个

2024-08-30 16:17 UTC, StageGuard commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    private val mutablePresentDanmaku: MutableList<PositionedDanmakuState> = mutableStateListOf()
聚合到一起可以更方便在 invalidate 时重新 populate 现有弹幕

2024-08-30 17:31 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuState.kt
> +    val enableColor: Boolean,
有没有 color 不影响 layout 吧

2024-08-31 01:30 UTC, StageGuard commented on danmaku/ui/commonMain/FloatingDanmakuTrack.kt
> +    override val onRemoveDanmaku: (DanmakuHostState.PositionedDanmakuState) -> Unit
经讨论是必须有的

2024-08-31 04:32 UTC, StageGuard commented on danmaku/ui/commonMain/DanmakuState.kt
> +    val enableColor: Boolean,
color 间接影响了 layout（color -> style -> layout）这里传进来是为了 keey immutability of DanmakuState

2024-08-31 04:38 UTC, StageGuard commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +                    }
在暂停和恢复的时候有用，如果直接用 withFrame 的时间将导致弹幕跳动，需要花费额外的精力重新计算位置

2024-08-31 04:40 UTC, StageGuard commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    internal var trackHeight by trackHeightState
for displaying debug props

2024-08-31 04:42 UTC, StageGuard commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    internal val bottomTrack: MutableList<FixedDanmakuTrack> = mutableListOf()
all for displaying debug props

2024-08-31 12:53 UTC, StageGuard commented on danmaku/ui/commonMain/FloatingDanmakuTrack.kt
> +            val timeDiff = (frameTimeNanos.value - placeFrameTimeNanos) / 1_000_000_000f
> 弹幕的首帧时间应该是一个内在属性, 需要使用 UI 运动时的第一帧, placeFrameTimeNanos 不行
> 而 place 和开始第一帧运动就是会差一小会的, 所以你的每一个弹幕最开始都会差一会

弹幕在 place 的时间一定是弹幕期望出现的精确帧时间，弹幕一定要在这个时间出现，不可以有偏差。

> 假设第 1000ms 时放置弹幕, 1025ms 才下一个 ui 帧, 那你的弹幕就瞬移了 25ms

这个是正常的卡顿，没办法避免，如果一定要将弹幕在 1025ms 从最左侧开始出现，那一定会导致弹幕慢了 25ms 出现在屏幕上。

2024-08-31 15:36 UTC, Him188 requested changes

2024-08-31 15:36 UTC, Him188 commented on danmaku/ui/commonMain/FloatingDanmakuTrack.kt
> +    override fun canPlace(danmaku: T, placeTimeNanos: Long): Boolean {
check 下

2024-08-31 15:36 UTC, Him188 commented on danmaku/ui/commonMain/FixedDanmakuTrack.kt
> +) : FrameTimeBasedDanmakuTrack<T>(frameTimeNanosState) {
Remove FrameTimeBasedDanmakuTrack

2024-08-31 15:36 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHostState.kt
> +    while (trySend(danmaku) == null) delay(50)
不可以 delay

2024-09-01 04:51 UTC, StageGuard commented on danmaku/ui/commonMain/FloatingDanmakuTrack.kt
> +            val timeDiff = (frameTimeNanos.value - placeFrameTimeNanos) / 1_000_000_000f
resolved

2024-09-02 08:45 UTC, Him188 commented
merge master please

2024-09-02 09:06 UTC, Him188 commented on danmaku/ui/commonMain/FixedDanmakuTrack.kt
> +        check(placeTimeNanos >= DanmakuTrack.NOT_PLACED) {
```suggestion
        check(placeTimeNanos == DanmakuTrack.NOT_PLACED || placeTimeNanos >= 0) {
```

2024-09-02 09:06 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHost.kt
> -    frozen: Boolean = false,
test 里不能有 while true delay 的 loop

2024-09-02 10:34 UTC, StageGuard commented on danmaku/ui/commonMain/DanmakuHost.kt
>          }
需要，轨道数量要依靠这个计算，速度比较慢

2024-09-02 10:49 UTC, Him188 commented on danmaku/ui/commonMain/DanmakuHost.kt
>          }
宽度可以直接set吧，高度 debounce

宽度直接更新仅影响 Canvas draw 弹幕，而且会让 PC 变大变小屏幕时更流畅？

2024-09-02 10:49 UTC, StageGuard commented on danmaku/ui/commonMain/DanmakuHost.kt
>          }
可以

2024-09-02 15:37 UTC, Him188 approved these changes

2024-09-02 17:13 UTC, merged