安卓自动隐藏控制器
open-ani/ani pull request #853
Opened 2024-08-30 12:49 UTC by NieR4ever

resolve #270

2024-08-30 13:18 UTC, Him188 commented
要把 autoAdvanceTime 关掉，否则 performClick 也会模拟时间前进直到自动隐藏

2024-08-30 13:19 UTC, Him188 reviewed
增加 test case

2024-08-30 14:23 UTC, Him188 commented
目前 pc 是有类似的测试的，可以找一下

2024-08-31 11:10 UTC, Him188 requested changes
辛苦再加几个测试 (见评论)

2024-08-31 11:10 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/guesture/VideoGestureHost.kt
> +                                    }
应该给 family 加一个新的属性例如 (`autoHideController`) 来决定是否需要自动隐藏. PC 需要设置该属性为 `false`, 因为 PC 仅在鼠标移动后才会显示一会.

如果默认是显示控制器, 是不是就不会自动隐藏?

---- 

增加测试用例:
1. 如果默认是显示控制器, 也要有自动隐藏

最好再加一个:
2. 用户点击屏幕显示控制器, 然后用户点击隐藏, 过了 1 秒用户又点击显示, advance 时间 2.5 秒, 控制器仍然显示, 再经过 0.5 秒, 也就是达到 `VIDEO_GESTURE_MOUSE_MOVE_SHOW_CONTROLLER_DURATION`, 才会隐藏控制器
> 这是为了保证这个 launch 会被 cancel 掉, 也就是说计时总是在每次点击时开始计时, 保证每次点击后控制器一定会显示 `VIDEO_GESTURE_MOUSE_MOVE_SHOW_CONTROLLER_DURATION`.

2024-08-31 11:16 UTC, Him188 commented
这个功能确实挺重要的, 我自己用也好多次想要

2024-08-31 12:38 UTC, NieR4ever commented on app/shared/video-player/src/commonMain/kotlin/ui/VideoControllerState.kt
> +        }
在显示控制器时滑动快进，会导致控制器隐藏，也许应该将这段代码移动到 VideoGestureHost 中

2024-08-31 12:40 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/VideoControllerState.kt
> +        }
确实, 感觉可以在滑动时 requestAlwaysOn

2024-09-01 10:25 UTC, NieR4ever commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +                },
1. 点击控制器里的按钮或者其他组件时会请求 always on
4. didClickBottomBar 是用来取消 scope.launch 的

2024-09-01 14:37 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeVideo.kt
> +
```suggestion
```

2024-09-01 14:37 UTC, Him188 commented on app/shared/src/desktopTest/kotlin/ui/subject/episode/EpisodeVideoControllerTest.kt
> +                                }
这样的话你本质上只是在测试你在这里写的代码, 而没有测试到生产的代码. 假设生产代码里 `EpisodeVideo` 里面改了一行有错误, 你的 test 并不能发现这个错误. 

一个解决办法是写一个 `EpisodeVideoDefatuls`:
```kotlin
object EpisodeVideoDefatuls

@Composable
fun EpisodeVideoDefatuls.DanmakuEditor(...)
```

把 `EpisodeVideo` 中的逻辑尽可能多地封装进去, 这样就能保证测试里面和生产都是一样的

2024-09-01 14:37 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/guesture/VideoGestureHost.kt
> +                        }
```suggestion
                        delay(VIDEO_GESTURE_TOUCH_SHOW_CONTROLLER_DURATION)
                        controllerState.toggleFullVisible(false)
```
其实可以简化成这样吧

2024-09-01 14:37 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/guesture/VideoGestureHost.kt
> +                                    controllerState.setRequestAlwaysOn(this, true)
使用 `rememberAlwaysOnRequester`, 它能有名字

2024-09-02 09:14 UTC, Him188 commented on app/shared/video-player/src/commonMain/kotlin/ui/guesture/VideoGestureHost.kt
> +                                    controllerState.setRequestAlwaysOn(this, true)
![image](https://github.com/user-attachments/assets/fe2d4b0a-0ae3-4348-9d30-8ef40c527329)

这里就能看到

2024-09-02 13:04 UTC, Him188 approved these changes
need QA before merge

2024-09-02 13:04 UTC, Him188 commented
resolve 一下 conflict?

2024-09-05 11:45 UTC, Him188 commented
QA OK

- 安卓播放器内打开侧边栏几秒后关闭侧边栏时直接隐藏了控制器
- 安卓播放器在弹出选倍速菜单后仍然会自动关闭

2024-09-05 11:47 UTC, merged

2024-09-05 11:49 UTC, Him188 commented
这两个问题优先级都不高, 不影响合并 PR, 开了 issue 以后可以解决