支持记录单集播放进度
open-ani/ani pull request #898
Opened 2024-09-07 09:19 UTC by NieR4ever

resolve #60 
不知道为什么安卓在 ready 阶段 seekTo 无效

2024-09-07 10:48 UTC, Him188 requested changes

2024-09-07 10:48 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/source/media/selector/MediaSelectorEvents.kt
> +    val onPreSelect: Flow<SelectEvent>
注释一下和 select 的区别

2024-09-07 10:48 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/repository/EpisodeHistoryRepository.kt
> +interface EpisodeHistoryRepository : Repository {
名字要跟播放有关系吧, `EpisodePlayHistoryRepository`?

2024-09-07 10:48 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +                episodeHistoryState.saveProgress()
应该写在 `switchEpisode` 里面?

2024-09-07 10:48 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/EpisodeHistoryState.kt
> +            repository.saveOrUpdate(currentEpisodeId, position)
后台读取 compose state 是 undefined behavior

2024-09-07 10:48 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/video/EpisodeHistoryState.kt
> +) : HasBackgroundScope by BackgroundScope(parentCoroutineContext) {
这个不需要在 UI 展示, 不需要写 UI state 吧

class EpisodeHistorySaver, 然后用 flow 和 suspend, 不需要使用 compose 的 `State`. 不应该 launch 我觉得 (让调用方去 launch)

2024-09-07 10:48 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/source/media/selector/MediaSelectorEvents.kt
> +    val onPreSelect: Flow<SelectEvent>
我感觉要叫 onBeforeSelect?

PreSelect 给我的感觉像是它之后一定会有 Select, 但实际上并不是

2024-09-07 10:50 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +        episodeHistoryState.saveProgress()
有个问题, 更多情况可能是 app 放后台, 一段时间后被杀掉. 被杀掉不会调用这个 stop

2024-09-11 18:37 UTC, Him188 commented on app/shared/src/commonMain/kotlin/data/source/media/selector/MediaSelectorEvents.kt
> +    val onBeforeSelect: Flow<SelectEvent>
```suggestion
    /**
     * 此事件会在 media 切换前 emit.
     * 注意, 只要 [MediaSelector.select] 被调用就会广播这个事件. 这也就包括了重复选择同一个 media. 
     * 所以在广播这个事件后不一定会广播 [onSelect].
     */
    val onBeforeSelect: Flow<SelectEvent>
```

2024-09-11 18:37 UTC, Him188 commented on app/shared/video-player/src/androidMain/kotlin/PlayerState.android.kt
> +//                            }
可以删掉然后留一个注释说明 VLC 的行为以及为什么我们不在这里面修改状态

2024-09-11 18:37 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +                            launchInMain { // android must call in main thread
```suggestion
                            withContext(Dispatchers.Main) { // android must call in main thread
```

2024-09-11 18:37 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +        savePlayProgress()
那假如先 PlaybackState.FINISHED, 再 `stopPlaying`, 这是不是会 save

2024-09-11 18:37 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +            }
为什么不能是 onSelect? 所有东西要切换 epId 一定要通过 `switchEpisode`, 而 `switchEpisode` 里面已经有一个 save 了

2024-09-11 18:37 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +            playerState.state.collect {
可不可以把这些逻辑剥离 ViewModel? 这个 VM 已经 800 行了.

```kotlin
val playbackProgressSaver = PlaybackProgressSaver(
    playBackState = playerState.map {  },
    loadSavedProgress = episodePlayHistoryRepository.get(epId),
    onSeek: suspend (Long) -> Unit,
    onSave: suspend (Long) -> Unit,
    backgroundScope.coroutineContext,
)
```

`PlaybackProgressSaver` 自动创建协程监听 flow.

`playbackProgressSaver.saveIfNeeded(current, duration)`

----

或者我们可能更应该先合入这个 PR, 然后把所有 player 相关功能, 例如自动切下一集或跳过 OP/ED, 都挪到一个单独地方例如 `PlayerFeatures`

2024-09-12 06:49 UTC, NieR4ever commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +            }
> 为什么不能是 onSelect? 

同一集切换数据源时 onselect 不会 emit

> 所有东西要切换 epId 一定要通过 switchEpisode, 而 switchEpisode 里面已经有一个 save 了

保存播放进度的入口有4个：退出播放页，切换剧集，同集切换数据源，暂停播放
其中 `切换剧集` 和 `同集切换数据源` 虽然都是切换数据源，但它们并不能合并成一个入口，因为 `切换数据源` 是依赖 `PlayerLauncher` collect 
 `mediaSelector.selected` 实现的，它会在 `mediaSelector.unselect()` 任意时间后发现 selected 已经改变，导致 `episodeId` 可能已经改变，从而将当前集的播放进度保存到新的剧集中
```kt
    fun switchEpisode(episodeId: Int) {
        savePlayProgress()
        episodeDetailsState.showEpisodes = false // 选择后关闭弹窗
        mediaSelector.unselect() // 否则不会自动选择
        playerState.stop()
        switchEpisodeCompleted.value = false // 要在修改 episodeId 之前才安全, 但会有极小的概率在 fetchSession 更新前有 mediaList 更新
        this.episodeId.value = episodeId // ep 要在取消选择 media 之后才能变, 否则会导致使用旧的 media
    }
```

2024-09-12 08:52 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +            playerState.state.collect {
我记得先合PR 吧

2024-09-12 08:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/subject/episode/EpisodeViewModel.kt
> +            }
OK, 把这个信息注释到代码里吧, 那个 launch 那里

2024-09-12 12:12 UTC, Him188 approved these changes

2024-09-12 13:37 UTC, merged