允许根据 peer 的信息拉黑恶意 BT 用户
open-ani/ani pull request #901
Opened 2024-09-07 15:06 UTC by StageGuard

resolve https://github.com/open-ani/ani/issues/862

2024-09-07 15:17 UTC, Him188 commented on torrent/anitorrent/include/plugin/peer_filter_plugin.h
> +//
please remove this

2024-09-07 15:17 UTC, Him188 commented on torrent/anitorrent/include/peer_filter.hpp
> +//
please remove this

2024-09-07 15:17 UTC, Him188 commented on torrent/anitorrent/include/peer_filter.hpp
> +    };
fields not initialized

2024-09-07 15:17 UTC, Him188 commented on torrent/anitorrent/include/plugin/peer_filter_plugin.h
> +    {
大括号 format 到同一行

2024-09-07 15:17 UTC, Him188 commented on torrent/anitorrent/include/plugin/peer_filter_plugin.h
> +        bool on_handshake(lt::span<char const> d) override
class 实现写到 .cpp 里, 否则会导致编译变慢

2024-09-07 15:24 UTC, StageGuard commented
我不懂 cpp，但是他出问题了
```
> Task :torrent:anitorrent:buildAnitorrent
MSBuild version 17.10.4+10fbfbf2e for .NET Framework

  torrent-rasterbar.vcxproj -> D:\UsfProfSG\Desktop\Projects\ani\torrent\anitorrent\build-ci\_deps\libtorrent-build\Debug\torrent-rasterbar.dll
  anitorrent_wrap.cpp
peer_filter.obj : error LNK2005: "void __cdecl anilt::drop_connection(struct libtorrent::peer_connection_handle)" (?drop_connection@anilt@@YAXUpeer_connection_handle@libtorrent@@@Z) ??? session_t.obj ??? [D:\UsfProfSG\Desktop\Projects\ani\torrent\anitorrent\build-ci\anitorrent.vcxproj]
peer_filter.obj : error LNK2005: "class std::shared_ptr<struct anilt::peer_info_t> __cdecl anilt::parse_peer_info(struct libtorrent::v1_2::peer_info const &)" (?parse_peer_info@anilt@@YA?AV?$shared_ptr@Upeer_info_t@anilt@@@std@@AEBUpeer_info@v1_2@libtorrent@@@Z) ??? session_t.obj ??? [D:\UsfProfSG\Desktop\Projects\ani\torrent\anitorrent\build-ci\anitorrent.vcxproj]
peer_filter.obj : error LNK2005: "class std::shared_ptr<struct libtorrent::torrent_plugin> __cdecl anilt::create_peer_filter(struct libtorrent::torrent_handle const &,class std::function<bool __cdecl(struct anilt::peer_info_t *)> const &)" (?create_peer_filter@anilt@@YA?AV?$shared_ptr@Utorrent_plugin@libtorrent@@@std@@AEBUtorrent_handle@libtorrent@@AEBV?$function@$$A6A_NPEAUpeer_info_t@anilt@@@Z@3@@Z) ??? session_t.obj ??? [D:\UsfProfSG\Desktop\Projects\ani\torrent\anitorrent\build-ci\anitorrent.vcxproj]
    ????? D:/UsfProfSG/Desktop/Projects/ani/torrent/anitorrent/build-ci/Debug/anitorrent.lib ??? D:/UsfProfSG/Desktop/Projects/ani/torrent/anitorrent/build-ci/Debug/anitorrent.exp
anitorrent_wrap.obj : error LNK2019: ????????? "public: virtual bool __cdecl anilt::peer_filter_t::on_filter(struct anilt::peer_info_t const &)" (?on_filter@peer_filter_t@anilt@@UEAA_NAEBUpeer_info_t@2@@Z),?? "public: virtual bool __cdecl SwigDirector_peer_filter_t::on_filter(struct anilt::peer_info_t const &)" (?on_filter@SwigDirector_peer_filter_t@@UEAA_NAEBUpeer_info_t@anilt@@@Z) ??????? [D:\UsfProfSG\Desktop\Projects\ani\torrent\anitorrent\build-ci\anitorrent.vcxproj]
D:\UsfProfSG\Desktop\Projects\ani\torrent\anitorrent\build-ci\Debug\anitorrent.dll : fatal error LNK1120: 1 ?????????? [D:\UsfProfSG\Desktop\Projects\ani\torrent\anitorrent\build-ci\anitorrent.vcxproj]

> Task :torrent:anitorrent:buildAnitorrent FAILED

```

2024-09-11 12:23 UTC, Him188 commented
wocao files changed 66

2024-09-11 18:13 UTC, Him188 requested changes

2024-09-12 03:04 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/PeerFilterSettings.kt
> +                            SideEffect { focusRequester.requestFocus() }
search bar 的行为比较夸张，这里只是一个简单的搜索过滤

2024-09-12 03:11 UTC, StageGuard commented on torrent/anitorrent/src/peer_filter.cpp
> +            info.pid.data(),
string 从 char array 构造不是会复制副本吗？

2024-09-12 03:23 UTC, StageGuard commented on torrent/impl/anitorrent/src/jvmMain/kotlin/session/SwigPeerInfo.kt
> +    override val flags: Long = native.flags
应该全是 =

2024-09-12 03:28 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/PeerFilterEditPane.kt
> +                MaterialTheme.typography.bodySmall.fontSize
那个就是 bodySmall

2024-09-12 03:34 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/foundation/richtext/impl/BBCode.kt
> +                val richText = try { BBCode.parse(code) } catch (ex: Exception) {
这里没有其他的 scope 能用

2024-09-12 03:37 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/foundation/richtext/impl/BBCode.kt
> +fun RichText.toUIRichElements(overrideTextSize: Float? = null): List<UIRichElement> = buildList {
move 了之后可能要改很多东西，评论相关的，以后再改

2024-09-12 03:43 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/foundation/richtext/impl/BBCode.kt
> +                val richText = try { BBCode.parse(code) } catch (ex: Exception) {
我觉得让 transform 里的 parse 跑在 background thread 就可以，从构造器传入的 context

2024-09-12 12:32 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +        AlertDialog(
这样会更好吗，为什么 desktop 在对话框放编辑框不好

2024-09-12 12:33 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +                    }
放 supporting 里感觉很奇怪

2024-09-12 12:52 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +        AlertDialog(
这样可以连续添加

2024-09-12 12:53 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +        AlertDialog(
对话框位置会在屏幕中心, 需要点击一个按钮然后又把鼠标挪走, 每次还只能添加一个东西

编辑的时候全屏焦点都聚焦在对话框上面, 没法参考已有的规则

2024-09-12 12:56 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +        AlertDialog(
https://m3.material.io/components/dialogs/guidelines#55bba362-7726-4868-a4a3-a283dc81b8a1

M3 虽然是允许的, 但我觉得这种添加过滤的场景应该要允许连续添加

我觉得 M3 示例的这个用对话框实现是因为他有不少选项, 而我们只需要一个 TextField 就行了. M3 示例如果不用对话框, 就需要弹出一个新页面, 那当然不如用对话框了

2024-09-12 12:57 UTC, Him188 commented on torrent/anitorrent/src/peer_filter.cpp
> +            info.pid.data(),
C++ 是直接设置指针吧

2024-09-12 12:59 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +        AlertDialog(
这个对话框要和其他东西交互，比如点确定后的那个错误提示，所以我觉得做成dialog也没问题。
关于连续添加的问题，可以设置为按回车就 perform click 确定，按 command+enter 就换行

2024-09-12 13:05 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +        AlertDialog(
错误提示应该做到编辑框的 supportingText 吧

2024-09-12 13:06 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +        AlertDialog(
@NieR4ever 来评评理

2024-09-12 13:06 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +        AlertDialog(
那还有需要把鼠标从边缘移动到最中心的问题怎么解决呢, 而且 dialog 是二级的, 编辑框一级, 直接点击就能编辑

2024-09-12 13:36 UTC, NieR4ever commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +        AlertDialog(
连续添加的场景肯定是放在一级页面比较好
但是对于黑名单来说连续添加的场景比较少见，常见的场景可能是从哪里复制来一批ip，想要一次性导入

2024-09-12 13:56 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +        AlertDialog(
什么折中说

2024-09-12 13:58 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/foundation/richtext/RichText.kt
> +    val FontSize: Float = 16f
hi, did you fix this

2024-09-12 14:00 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/foundation/richtext/RichText.kt
> +    val FontSize: Float = 16f
wangle

2024-09-12 14:01 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +        AlertDialog(
确实应该更频繁的场景是一批 ip

2024-09-12 14:02 UTC, StageGuard commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +        AlertDialog(
> 那还有需要把鼠标从边缘移动到最中心的问题怎么解决呢, 而且 dialog 是二级的, 编辑框一级, 直接点击就能编辑

打开 dialog 直接聚焦到 textfield，输入完或者粘贴完按回车，完全不用动鼠标

2024-09-12 17:36 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/BlockListEditPane.kt
> +        AlertDialog(
See https://github.com/open-ani/ani/issues/923

2024-09-12 17:37 UTC, Him188 commented on app/shared/src/commonMain/kotlin/ui/foundation/richtext/RichText.kt
> +    val FontSize: Float = 16f
minor problem, 算了

2024-09-12 17:37 UTC, Him188 approved these changes

2024-09-12 17:37 UTC, merged