Respect to canonical M3 color system and window insets
open-ani/ani pull request #910
Opened 2024-09-09 22:29 UTC by Him188

- 使用 M3 标准颜色
- 规范使用 Window Insets
- 安卓顺便支持了动态颜色 (API 31+)

2024-09-10 18:57 UTC, Him188 commented
@StageGuard @NieR4ever 评价一下?

2024-09-10 23:35 UTC, Him188 commented
感觉可能还是要先把浅色退回旧版配色，深色使用新版（M3 原版）。因为目前 UI 设计搭配 M3 标准颜色风格在默认浅色主题下不好看（也有一些 accessibility 问题）。

允许新版动态配色。动态配色是用户自己选的，而且可以关闭。

这样就可以合并 Window Insets 的修复和使用 1.7 新 API。

我琢磨了两天也没琢磨明白如何设计首页 UI 好看，这是一个很大的问题，需要为整个 APP 重新设计 UI。

2024-09-11 02:40 UTC, StageGuard requested changes
![image](https://github.com/user-attachments/assets/c72d720a-2bc2-49c8-8736-3da411b9d5c2)

设置项目的颜色不应该和上面的颜色一样，我觉得在亮色模式下应该直接去掉设置项目的颜色

![image](https://github.com/user-attachments/assets/c980bf1e-4eec-460c-b399-6962613b84c7)

缓存组的卡片有点暗了，剧集的颜色太灰了

2024-09-11 07:20 UTC, Him188 commented
设置目前没法去掉底色，需要有 grouping 作用

2024-09-11 07:23 UTC, StageGuard commented
> 设置目前没法去掉底色，需要有 grouping 作用

why? 我觉得只要有 primary color 的标签就可以分隔各个 group，根本不需要底色和 group 之间这么大的 padding

2024-09-11 07:24 UTC, Him188 commented
浅色确实还是弄回旧配色吧，设置页需要改成导航后才能调配色

2024-09-11 08:51 UTC, Him188 commented
> 我觉得只要有 primary color 的标签就可以分隔各个 group，根本不需要底色和 group 之间这么大的 padding。 

确实，这个 PR 里改掉

> 而且 TabRow 其实也不适合在 Android 上的操作习惯，一般使用二级菜单

记录一下：讨论决定之后再统一重构成二级菜单（因为要考虑双端）

2024-09-12 10:24 UTC, Him188 commented
![image](https://github.com/user-attachments/assets/fc7b0d88-be81-4fe9-badc-03ccd3b76162)

![image](https://github.com/user-attachments/assets/9f078769-0f21-495a-bd80-3b49f2891eb3)

改回去纯白了

2024-09-12 14:05 UTC, merged

2024-09-20 19:38 UTC, wan0ge commented
缓存界面考虑做同番剧不同集数折叠吗？不单个分列同一部番剧堆在一起，子集只显示集名称那一块，超过一定量折叠像抽屉一样，在此基础上还可以做丝滑的抽屉动画

2024-09-20 21:10 UTC, Him188 commented
> 缓存界面考虑做同番剧不同集数折叠吗？不单个分列同一部番剧堆在一起，子集只显示集名称那一块，超过一定量折叠像抽屉一样，在此基础上还可以做丝滑的抽屉动画

这个有 issue