Allow always block peer with unexpected fingerprint.
open-ani/ani pull request #980
Opened 2024-09-20 10:02 UTC by StageGuard

2024-09-20 13:52 UTC, Him188 requested changes

2024-09-20 13:52 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/models/preference/TorrentPeerConfig.kt
> +    val blockUnexpectedId: Boolean = false,
默认 true?

2024-09-20 13:52 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/tools/torrent/PeerFilterType.kt
> +    override fun onFilter(info: PeerInfo): Boolean {
这 filter 怎么是返回 `true` 剔除, 跟 `List.filter` 行为不一致, 反习惯

2024-09-20 13:52 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/tools/torrent/PeerFilterType.kt
> +    override fun onFilter(info: PeerInfo): Boolean {
但不要在这个 PR 里解决这个问题

2024-09-20 13:52 UTC, Him188 commented on torrent/anitorrent/src/jvmMain/kotlin/session/SwigPeerInfo.kt
> +    override val id: CharArray = native.peer_id.toCharArray()
C++ char 实际上对应 Kotlin byte

2024-09-20 13:52 UTC, Him188 commented on app/shared/ui-settings/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/PeerFilterSettingsState.kt
> +        copy = { copy(enableIdFilter = it, blockUnexpectedId = false) },
改一个设置的时候不应该副作用修改别的设置

应该在你引擎逻辑里总的判断一下 idFilterEnabled

2024-09-20 13:52 UTC, Him188 commented on app/shared/ui-settings/src/commonMain/kotlin/ui/settings/tabs/media/torrent/peer/PeerFilterEditPane.kt
> +private fun ExpandableSwitchItem(
以后有这种修改先直接 commit 到 main, 不要放到 PR 里产生 (许多) 无关变更

2024-09-20 13:52 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/data/models/preference/TorrentPeerConfig.kt
> +    val blockUnexpectedId: Boolean = false,
"expect" 的语义不合适吧

我们并没有 expect 什么. 用 invalid 比较合适?

2024-09-20 13:52 UTC, Him188 commented on app/shared/app-data/src/commonMain/kotlin/tools/torrent/PeerFilterType.kt
> +        if (!idArr.drop(1).contains(FINGERPRINT_TRIM)) return true
drop 会 copy 一次, 造成内存浪费

用 lastIndexOf, 判断 != 0

2024-09-20 13:54 UTC, Him188 commented on torrent/anitorrent/src/jvmMain/kotlin/session/SwigPeerInfo.kt
> +    override val id: CharArray = native.peer_id.toCharArray()
Key Differences
Encoding and Size:

C++ char is 1 byte (ASCII), while Kotlin Char is 2 bytes (UTF-16).
Type Representation:

C++ char is more closely related to an integer, while Kotlin Char is a distinct type with additional properties and methods.
Character Handling:

Kotlin Char has built-in methods for common character checks (e.g., isLetter(), isWhitespace()), whereas in C++ you typically rely on functions like isalpha() from <cctype>.
String Handling:

C++ uses null-terminated character arrays for strings, whereas Kotlin uses immutable String objects.

2024-09-21 04:17 UTC, StageGuard commented on torrent/anitorrent/src/jvmMain/kotlin/session/SwigPeerInfo.kt
> +    override val id: CharArray = native.peer_id.toCharArray()
那我觉得应该也没问题，c++ char to kotlin char 也不会产生错误，也方便做判断

2024-09-21 10:34 UTC, Him188 commented on torrent/anitorrent/src/jvmMain/kotlin/session/SwigPeerInfo.kt
> +    override val id: CharArray = native.peer_id.toCharArray()
它是byte，用char表示要涉及编码，会显著慢而且占位置

2024-09-21 10:37 UTC, StageGuard commented on torrent/anitorrent/src/jvmMain/kotlin/session/SwigPeerInfo.kt
> +    override val id: CharArray = native.peer_id.toCharArray()
那就没办法通过 regex 匹配过滤

2024-09-21 10:40 UTC, Him188 commented on torrent/anitorrent/src/jvmMain/kotlin/session/SwigPeerInfo.kt
> +    override val id: CharArray = native.peer_id.toCharArray()
ok fine

2024-09-21 10:40 UTC, Him188 approved these changes

2024-09-21 10:40 UTC, merged